# Generated by Django 4.1 on 2022-08-29 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.TextField(primary_key=True, serialize=False)),
                ('has_replays', models.BooleanField()),
                ('num_difficulties', models.IntegerField()),
            ],
            options={
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Regular'), (2, 'Tas'), (3, 'Unlisted'), (4, 'Private')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=50000)),
                ('points', models.BigIntegerField()),
                ('rep_date', models.DateTimeField()),
                ('rep_points', models.BigIntegerField()),
                ('rep_name', models.TextField()),
                ('rep_difficulty', models.IntegerField()),
                ('rep_slowdown', models.FloatField(blank=True, null=True)),
                ('rep_clear', models.IntegerField(blank=True, null=True)),
                ('rep_spellpracticeid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['shot', 'rep_difficulty', '-points'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('replay', models.BinaryField(max_length=1000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replays.game')),
            ],
        ),
        migrations.CreateModel(
            name='ReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_file', models.BinaryField(blank=True, max_length=1000000, null=True)),
                ('is_good', models.BooleanField()),
                ('video_link', models.TextField(blank=True, max_length=1000, null=True)),
                ('replay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='replays.replay')),
            ],
        ),
        migrations.AddField(
            model_name='replay',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='replays.shot'),
        ),
        migrations.AddField(
            model_name='replay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(models.F('shot_id'), models.F('game'), name='unique_shot_per_game'),
        ),
        migrations.AddConstraint(
            model_name='replay',
            constraint=models.CheckConstraint(check=models.Q(('rep_difficulty__gte', 0)), name='difficulty_gte_0'),
        ),
    ]
