# Generated by Django 4.1 on 2022-09-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayfile',
            name='is_good',
        ),
        migrations.RemoveField(
            model_name='replayfile',
            name='points',
        ),
        migrations.AddField(
            model_name='replay',
            name='is_good',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replay',
            name='rep_points',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
