# Generated by Django 4.1 on 2022-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0002_replaystages_alter_replay_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayfile',
            name='is_good',
        ),
        migrations.AddField(
            model_name='replay',
            name='is_good',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
