# Generated by Django 4.1 on 2022-09-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0002_remove_replayfile_is_good_remove_replayfile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
