# Generated by Django 4.1 on 2022-09-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0003_replay_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('piv', models.IntegerField(blank=True, null=True)),
                ('graze', models.IntegerField(blank=True, null=True)),
                ('point_items', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('lives', models.IntegerField(blank=True, null=True)),
                ('life_pieces', models.IntegerField(blank=True, null=True)),
                ('bombs', models.IntegerField(blank=True, null=True)),
                ('bomb_pieces', models.IntegerField(blank=True, null=True)),
                ('th06_rank', models.IntegerField(blank=True, null=True)),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replays.replay')),
            ],
        ),
        migrations.AddConstraint(
            model_name='replaystage',
            constraint=models.UniqueConstraint(fields=('replay', 'stage'), name='unique_stage_per_game'),
        ),
    ]
