# Generated by Django 4.1 on 2022-09-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0004_route_route_unique_route_per_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='replays.route'),
        ),
    ]
