# Generated by Django 4.1 on 2022-09-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0005_alter_replaystage_score'),
        ('replays', '0005_replay_route'),
    ]

    operations = [
    ]
