# Generated by Django 4.1 on 2022-09-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0006_merge_0005_alter_replaystage_score_0005_replay_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaystage',
            name='th07_cherry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaystage',
            name='th07_cherrymax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
