# Generated by Django 4.1 on 2022-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0007_replaystage_th07_cherry_replaystage_th07_cherrymax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['shot', 'difficulty', '-score']},
        ),
        migrations.RenameField(
            model_name='replay',
            old_name='rep_points',
            new_name='rep_score',
        ),
        migrations.RenameField(
            model_name='replay',
            old_name='points',
            new_name='score',
        ),
    ]
