# Generated by Django 4.1 on 2022-10-22 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0008_alter_replay_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryreplayfile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
