# Generated by Django 4.1 on 2022-11-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0009_alter_temporaryreplayfile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='name',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
