# Generated by Django 4.1 on 2022-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0009_alter_temporaryreplayfile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='category',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Tas'), (3, 'Unusual'), (4, 'Private')]),
        ),
    ]
