# Generated by Django 4.1 on 2022-11-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0010_alter_replay_category'),
        ('replays', '0010_replay_name'),
    ]

    operations = [
    ]
