# Generated by Django 4.1 on 2022-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0010_alter_replay_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='is_clear',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
