# Generated by Django 4.1 on 2022-11-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0012_replay_is_clear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='category',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'TAS'), (3, 'Unusual'), (4, 'Private')]),
        ),
    ]
