# Generated by Django 4.1 on 2022-11-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0013_alter_replay_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaystage',
            name='th08_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
