# Generated by Django 4.1.4 on 2022-12-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0015_remove_replaystage_th08_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaystage',
            name='th09_p1_cpu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaystage',
            name='th09_p2_cpu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaystage',
            name='th09_p2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaystage',
            name='th09_p2_shot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='replays.shot'),
        ),
    ]
