# Generated by Django 4.1.4 on 2022-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0017_replay_spell_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='replay_type',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Stage Practice'), (3, 'Spell Practice')], default=1),
            preserve_default=False,
        ),
    ]
