# Generated by Django 4.1.4 on 2022-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0018_replay_replay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='replay_type',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Stage Practice'), (3, 'Spell Practice'), (4, 'PVP')]),
        ),
    ]
