# Generated by Django 4.1.4 on 2022-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0019_alter_replay_replay_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='replay',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('replay_type', 1), ('spell_card_id__isnull', True)), models.Q(('replay_type', 2), ('spell_card_id__isnull', True)), models.Q(('replay_type', 3), ('spell_card_id__isnull', False)), models.Q(('replay_type', 4), ('spell_card_id__isnull', True)), _connector='OR'), name='replay_type_spell_card_id_isnull'),
        ),
    ]
