# Generated by Django 4.1.4 on 2022-12-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0020_replay_replay_type_spell_card_id_isnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaystage',
            name='score',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
