# Generated by Django 4.1.4 on 2023-01-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0022_replay_slowdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaystage',
            name='extends',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaystage',
            name='th13_trance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
