# Generated by Django 4.1.4 on 2023-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0024_alter_replay_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaystage',
            name='th16_season_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
