# Generated by Django 4.1.6 on 2023-02-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0024_alter_replay_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryReplayFile',
        ),
    ]
