# Generated by Django 4.1.7 on 2023-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0024_alter_replay_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="replaystage",
            options={"ordering": ["replay", "stage"]},
        ),
        migrations.AddIndex(
            model_name="replaystage",
            index=models.Index(fields=["replay", "stage"], name="replay_and_stage"),
        ),
    ]
