# Generated by Django 4.1.6 on 2023-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0025_delete_temporaryreplayfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='category',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Tool-Assisted'), (3, 'Unusual'), (4, 'Pending')]),
        ),
        migrations.AlterField(
            model_name='replay',
            name='is_clear',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='replay',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 4), ('is_clear__isnull', True)), ('is_clear__isnull', False), _connector='OR'), name='is_clear_null_for_pending'),
        ),
    ]
