# Generated by Django 4.1.6 on 2023-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0025_delete_temporaryreplayfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='category',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Tool-Assisted'), (3, 'Unusual'), (4, 'Pending')]),
        ),
    ]
