# Generated by Django 4.1.6 on 2023-02-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0025_alter_replaystage_options_and_more'),
        ('replays', '0025_replaystage_th16_season_power'),
    ]

    operations = [
    ]
