# Generated by Django 4.1.6 on 2023-02-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0026_alter_replay_category_alter_replay_is_clear_and_more'),
        ('replays', '0026_merge_20230221_1947'),
    ]

    operations = [
    ]
