# Generated by Django 4.1.7 on 2023-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0027_replayfile_replay_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replay",
            name="category",
            field=models.IntegerField(
                choices=[(1, "Regular"), (2, "Tool-Assisted"), (3, "Unusual")]
            ),
        ),
    ]
