# Generated by Django 4.1.7 on 2023-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0028_alter_replay_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="miss_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="no_bomb",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
