# Generated by Django 4.1.7 on 2023-03-28 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0031_alter_replay_user_alter_temporaryreplayfile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="imported_username",
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="replay",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
