# Generated by Django 4.1.7 on 2023-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0032_replay_imported_username_alter_replay_created"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="replay",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("imported_username__isnull", False), ("user__isnull", True)
                    ),
                    models.Q(
                        ("imported_username__isnull", True), ("user__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="user_xor_imported_username_isnull",
            ),
        ),
    ]
