# Generated by Django 4.1.7 on 2023-04-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0033_replay_user_xor_imported_username_isnull"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replay",
            name="category",
            field=models.IntegerField(
                choices=[(1, "Standard"), (2, "Tool-Assisted"), (3, "Unusual")]
            ),
        ),
        migrations.AlterField(
            model_name="replay",
            name="replay_type",
            field=models.IntegerField(
                choices=[
                    (1, "Full Game"),
                    (2, "Stage Practice"),
                    (3, "Spell Practice"),
                    (4, "PVP"),
                ]
            ),
        ),
    ]
