# Generated by Django 4.1.7 on 2023-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0034_alter_replay_category_alter_replay_replay_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="replay",
            name="user_xor_imported_username_isnull",
        ),
        migrations.AddConstraint(
            model_name="replay",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("imported_username__isnull", False),
                    _connector="OR",
                ),
                name="user_or_imported_username_is_nonnull",
            ),
        ),
    ]
