# Generated by Django 4.1.7 on 2023-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0034_alter_replay_category_alter_replay_replay_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="listed",
            field=models.BooleanField(default=True),
        ),
    ]
