# Generated by Django 4.1.7 on 2023-05-14 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0035_replay_listed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="replay",
            old_name="listed",
            new_name="is_listed",
        ),
    ]
