# Generated by Django 4.2.1 on 2023-05-20 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0035_replaystage_th128_motivation_and_more"),
        ("replays", "0036_rename_listed_replay_is_listed"),
    ]

    operations = []
