# Generated by Django 4.1.7 on 2023-05-24 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0035_remove_replay_user_xor_imported_username_isnull_and_more"),
        ("replays", "0037_merge_20230520_2150"),
    ]

    operations = []
