# Generated by Django 4.2.4 on 2023-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0039_replaystage_th128_frozen_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="has_multiple_shots",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="has_routes",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="has_subshots",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
