# Generated by Django 4.2.4 on 2025-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0043_replay_legacy_rank"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="replay",
            name="difficulty_gte_0",
        ),
        migrations.AlterField(
            model_name="replay",
            name="difficulty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="replay",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("difficulty__gte", 0),
                    ("difficulty__isnull", True),
                    _connector="OR",
                ),
                name="difficulty_gte_0",
            ),
        ),
    ]
