# Generated by Django 4.2.4 on 2026-04-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0044_remove_replay_difficulty_gte_0_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="scene_game_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="scene_game_scene",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="replay",
            name="replay_type",
            field=models.IntegerField(
                choices=[
                    (1, "Full Game"),
                    (2, "Stage Practice"),
                    (3, "Spell Practice"),
                    (4, "PVP"),
                    (5, "Scene Game"),
                ]
            ),
        ),
    ]
