# Generated by Django 4.2.4 on 2026-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0045_replay_scene_game_level_replay_scene_game_scene_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="replay",
            name="replay_type_spell_card_id_isnull",
        ),
        migrations.AddConstraint(
            model_name="replay",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("replay_type", 1), ("spell_card_id__isnull", True)),
                    models.Q(("replay_type", 2), ("spell_card_id__isnull", True)),
                    models.Q(("replay_type", 3), ("spell_card_id__isnull", False)),
                    models.Q(("replay_type", 4), ("spell_card_id__isnull", True)),
                    models.Q(("replay_type", 5), ("spell_card_id__isnull", True)),
                    _connector="OR",
                ),
                name="replay_type_spell_card_id_isnull",
            ),
        ),
    ]
