# Generated by Django 4.2.4 on 2026-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0046_remove_replay_replay_type_spell_card_id_isnull_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="num_scene_game_levels",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_scene_game_scenes",
            field=models.IntegerField(default=0),
        ),
    ]
