# Generated by Django 4.2.4 on 2026-04-24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0047_game_num_scene_game_levels_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE VIEW replays_rank
AS
SELECT row_number() over () as id, replay, score, shot_id, difficulty, route_id, category, scene_game_level, scene_game_scene, place
FROM (
SELECT id as replay, score, shot_id, difficulty, route_id, category, scene_game_level, scene_game_scene, rank() OVER (PARTITION BY shot_id, difficulty, route_id, category, scene_game_level, scene_game_scene ORDER BY score DESC, created, id) as place
FROM replays_replay
WHERE replay_type IN (1, 5)  -- FULL_GAME, SCENE_GAME
AND category = 1  -- STANDARD
) AS ranked
WHERE place <= 3
ORDER BY shot_id, difficulty, route_id, category, scene_game_level, scene_game_scene, place desc
;
                          """,
            reverse_sql="""
DROP VIEW IF EXISTS replays_rank;
""",
        )
    ]
