# Generated by Django 5.2.14 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0048_update_replay_rank_view_for_scene_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="th03_is_netplay",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_match_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_p1_name",
            field=models.CharField(blank=True, max_length=57, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_p1_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_p2_name",
            field=models.CharField(blank=True, max_length=57, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_p2_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_recorder_role",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_recorder_source",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replay",
            name="th03_ruleset",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replaystage",
            name="th03_player_cpu",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replaystage",
            name="th03_opponent_cpu",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replaystage",
            name="th03_opponent_score",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replaystage",
            name="th03_opponent_shot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="replays.shot",
            ),
        ),
    ]
