# Generated by Django 5.2.14 on 2026-09-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0048_update_replay_rank_view_for_scene_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="replaystage",
            name="misses",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
