# Generated by Django 5.2.14 on 2026-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0049_replaystage_misses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replay",
            name="replay_type",
            field=models.IntegerField(
                choices=[
                    (1, "Full Game"),
                    (2, "Stage Practice"),
                    (3, "Spell Practice"),
                    (4, "PVP"),
                    (5, "Scene Game"),
                    (6, "New Classic: Challenge"),
                ]
            ),
        ),
    ]
