# Generated by Django 5.2.14 on 2026-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0051_remove_replay_replay_type_spell_card_id_isnull_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="version",
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
