from immutabledict import immutabledict
from django.utils.translation import get_language

spell_names_en = immutabledict(
    {
        "th08": (
            'Firefly Sign "Earthly Meteor"',
            'Firefly Sign "Earthly Comet"',
            'Lamp Sign "Firefly Phenomenon"',
            'Lamp Sign "Firefly Phenomenon"',
            'Lamp Sign "Firefly Phenomenon"',
            'Lamp Sign "Firefly Phenomenon"',
            'Wriggle Sign "Little Bug"',
            'Wriggle Sign "Little Bug Storm"',
            'Wriggle Sign "Nightbug Storm"',
            'Wriggle Sign "Nightbug Tornado"',
            'Hidden Bug "Endless Night Seclusion"',
            'Hidden Bug "Endless Night Seclusion"',
            'Hidden Bug "Endless Night Seclusion"',
            'Vocal Sign "Hooting in the Night"',
            'Vocal Sign "Hooting in the Night"',
            'Vocal Sign "Howl of the Horned Owl"',
            'Vocal Sign "Howl of the Horned Owl"',
            'Moth Sign "Hawk Moth\'s Insect Curse"',
            'Moth Sign "Hawk Moth\'s Insect Curse"',
            'Toxin Sign "Poisonous Moth\'s Scales"',
            'Deadly Toxin "Poisonous Moth\'s Dance in the Dark"',
            'Hawk Sign "Ill-Starred Dive"',
            'Hawk Sign "Ill-Starred Dive"',
            'Hawk Sign "Ill-Starred Dive"',
            'Hawk Sign "Ill-Starred Dive"',
            'Night-Blindness "Song of the Night Sparrow"',
            'Night-Blindness "Song of the Night Sparrow"',
            'Night-Blindness "Song of the Night Sparrow"',
            'Night-Blindness "Song of the Night Sparrow"',
            'Night-Sparrow "Midnight Chorus-Master"',
            'Night-Sparrow "Midnight Chorus-Master"',
            'Night-Sparrow "Midnight Chorus-Master"',
            'Spiritual Birth "First Pyramid"',
            'Spiritual Birth "First Pyramid"',
            'Spiritual Birth "First Pyramid"',
            'Spiritual Birth "First Pyramid"',
            'Origin Sign "Ephemerality 137"',
            'Origin Sign "Ephemerality 137"',
            'Origin Sign "Ephemerality 137"',
            'Ambition Sign "Buretsu Crisis"',
            'Ambition Sign "Masakado Crisis"',
            'Ambition Sign "Yoshimitsu Crisis"',
            'Ambition Sign "General Headquarters Crisis"',
            'Land Sign "Three Sacred Treasures - Sword"',
            'Land Sign "Three Sacred Treasures - Orb"',
            'Land Sign "Three Sacred Treasures - Mirror"',
            'Land Scheme "Three Sacred Treasures - Country"',
            'Ending Sign "Phantasmal Emperor"',
            'Ending Sign "Phantasmal Emperor"',
            'Pseudo-History "The Legend of Gensokyo"',
            'Pseudo-History "The Legend of Gensokyo"',
            'Future "Gods\' Realm"',
            'Future "Gods\' Realm"',
            'Future "Gods\' Realm"',
            'Dream Sign "Duplex Barrier"',
            'Dream Sign "Duplex Barrier"',
            'Dream Land "Great Duplex Barrier"',
            'Dream Land "Great Duplex Barrier"',
            'Spirit Sign "Fantasy Seal -Spread-"',
            'Spirit Sign "Fantasy Seal -Spread-"',
            'Scattered Spirit "Fantasy Seal -Worn-"',
            'Scattered Spirit "Fantasy Seal -Worn-"',
            'Dream Sign "Evil-Sealing Circle"',
            'Dream Sign "Evil-Sealing Circle"',
            'Divine Arts "Omnidirectional Oni-Binding Circle"',
            'Divine Arts "Omnidirectional Dragon-Slaying Circle"',
            'Spirit Sign "Fantasy Seal -Concentrate-"',
            'Spirit Sign "Fantasy Seal -Concentrate-"',
            'Migrating Spirit "Fantasy Seal -Marred-"',
            'Migrating Spirit "Fantasy Seal -Marred-"',
            'Boundary "Duplex Danmaku Barrier"',
            'Boundary "Duplex Danmaku Barrier"',
            'Great Barrier "Hakurei Danmaku Barrier"',
            'Great Barrier "Hakurei Danmaku Barrier"',
            'Divine Spirit "Fantasy Seal -Blink-"',
            'Divine Spirit "Fantasy Seal -Blink-"',
            'Divine Spirit "Fantasy Seal -Blink-"',
            'Magic Sign "Milky Way"',
            'Magic Sign "Milky Way"',
            'Magic Space "Asteroid Belt"',
            'Magic Space "Asteroid Belt"',
            'Magic Sign "Stardust Reverie"',
            'Magic Sign "Stardust Reverie"',
            'Black Magic "Event Horizon"',
            'Black Magic "Event Horizon"',
            'Love Sign "Non-Directional Laser"',
            'Love Sign "Non-Directional Laser"',
            'Love Storm "Starlight Typhoon"',
            'Love Storm "Starlight Typhoon"',
            'Love Sign "Master Spark"',
            'Love Sign "Master Spark"',
            'Loving Heart "Double Spark"',
            'Loving Heart "Double Spark"',
            'Light Sign "Earthlight Ray"',
            'Light Sign "Earthlight Ray"',
            'Light Blast "Shoot the Moon"',
            'Light Blast "Shoot the Moon"',
            'Magicannon "Final Spark"',
            'Magicannon "Final Spark"',
            'Magicannon "Final Master Spark"',
            'Wave Sign "Red-Eyed Hypnosis (Mind Shaker)"',
            'Wave Sign "Red-Eyed Hypnosis (Mind Shaker)"',
            'Illusion Wave "Red-Eyed Hypnosis (Mind Blowing)"',
            'Illusion Wave "Red-Eyed Hypnosis (Mind Blowing)"',
            'Lunatic Sign "Hallucinogenic Tuning (Visionary Tuning)"',
            'Lunatic Sign "Hallucinogenic Tuning (Visionary Tuning)"',
            'Lunatic Gaze "Lunatic Stare Tuning (Illusion Seeker)"',
            'Lunatic Gaze "Lunatic Stare Tuning (Illusion Seeker)"',
            'Loafing Sign "Life & Spirit Stopping (Idling Wave)"',
            'Loafing Sign "Life & Spirit Stopping (Idling Wave)"',
            'Indolence "Life & Spirit Stopping (Mind Stopper)"',
            'Indolence "Life & Spirit Stopping (Mind Stopper)"',
            'Spread Sign "Moon of Truth (Invisible Full Moon)"',
            'Spread Sign "Moon of Truth (Invisible Full Moon)"',
            'Spread Sign "Moon of Truth (Invisible Full Moon)"',
            'Spread Sign "Moon of Truth (Invisible Full Moon)"',
            'Lunar Eyes "Lunar Rabbit\'s Remote Mesmerism (Tele-Mesmerism)"',
            'Lunar Eyes "Lunar Rabbit\'s Remote Mesmerism (Tele-Mesmerism)"',
            'Lunar Eyes "Lunar Rabbit\'s Remote Mesmerism (Tele-Mesmerism)"',
            'Spacesphere "Earth in a Pot"',
            'Spacesphere "Earth in a Pot"',
            'Spacesphere "Earth in a Pot"',
            'Spacesphere "Earth in a Pot"',
            'Awakened God "Memories of the Age of the Gods"',
            'Awakened God "Memories of the Age of the Gods"',
            'God Sign "Genealogy of the Celestials"',
            'God Sign "Genealogy of the Celestials"',
            'Revival "Seimei Yūgi -Life Game-"',
            'Revival "Seimei Yūgi -Life Game-"',
            'Resurrection "Rising Game"',
            'Resurrection "Rising Game"',
            'Leading God "Omoikane\'s Device"',
            'Leading God "Omoikane\'s Device"',
            'Mind of God "Omoikane\'s Brain"',
            'Mind of God "Omoikane\'s Brain"',
            'Curse of the Heavens "Apollo 13"',
            'Curse of the Heavens "Apollo 13"',
            'Curse of the Heavens "Apollo 13"',
            'Curse of the Heavens "Apollo 13"',
            'Esoterica "Astronomical Entombing"',
            'Esoterica "Astronomical Entombing"',
            'Esoterica "Astronomical Entombing"',
            'Esoterica "Astronomical Entombing"',
            'Forbidden Elixir "Hourai Elixir"',
            'Forbidden Elixir "Hourai Elixir"',
            'Forbidden Elixir "Hourai Elixir"',
            'Forbidden Elixir "Hourai Elixir"',
            'Medicine Sign "Galaxy in a Pot"',
            'Medicine Sign "Galaxy in a Pot"',
            'Medicine Sign "Galaxy in a Pot"',
            'Medicine Sign "Galaxy in a Pot"',
            "Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\"",
            "Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\"",
            'Divine Treasure "Brilliant Dragon Bullet"',
            'Divine Treasure "Brilliant Dragon Bullet"',
            'Impossible Request "Buddha\'s Stone Bowl -Indomitable Will-"',
            'Impossible Request "Buddha\'s Stone Bowl -Indomitable Will-"',
            'Divine Treasure "Buddhist Diamond"',
            'Divine Treasure "Buddhist Diamond"',
            'Impossible Request "Robe of Fire Rat -Patient Mind-"',
            'Impossible Request "Robe of Fire Rat -Patient Mind-"',
            'Divine Treasure "Salamander Shield"',
            'Divine Treasure "Salamander Shield"',
            'Impossible Request "Swallow\'s Cowrie Shell -Everlasting Life-"',
            'Impossible Request "Swallow\'s Cowrie Shell -Everlasting Life-"',
            'Divine Treasure "Life Spring Infinity"',
            'Divine Treasure "Life Spring Infinity"',
            'Impossible Request "Bullet Branch of Hourai -Rainbow Danmaku-"',
            'Impossible Request "Bullet Branch of Hourai -Rainbow Danmaku-"',
            'Divine Treasure "Jeweled Branch of Hourai -Dreamlike Paradise-"',
            'Divine Treasure "Jeweled Branch of Hourai -Dreamlike Paradise-"',
            '"End of Imperishable Night -New Moon-"',
            '"End of Imperishable Night -Crescent Moon-"',
            '"End of Imperishable Night -1st Quarter\'s Moon-"',
            '"End of Imperishable Night -Matsuyoi-"',
            '"End of Imperishable Night -11 o\'Clock-"',
            '"End of Imperishable Night -Half to Midnight-"',
            '"End of Imperishable Night -Midnight-"',
            '"End of Imperishable Night -Half Past Midnight-"',
            '"End of Imperishable Night -1 o\'Clock-"',
            '"End of Imperishable Night -Half Past 1-"',
            '"End of Imperishable Night -Dead of Night-"',
            '"End of Imperishable Night -Half Past 2-"',
            '"End of Imperishable Night -3 o\'Clock-"',
            '"End of Imperishable Night -Half Past 3-"',
            '"End of Imperishable Night -4 o\'Clock-"',
            '"End of Imperishable Night -Half Past 4-"',
            '"End of Imperishable Night -Morning Mist-"',
            '"End of Imperishable Night -Dawn-"',
            '"End of Imperishable Night -Morning Star-"',
            '"End of Imperishable Night -Rising World-"',
            'Past "Old History of an Untrodden Land -Old History-"',
            'Reincarnation "Ichijou Returning Bridge"',
            'Future "New History of Fantasy -Next History-"',
            'Limiting Edict "Curse of Tsuki-no-Iwakasa"',
            'Undying "Fire Bird -Feng Wing Ascension-"',
            'Fujiwara "Wounds of Metsuzai Temple"',
            'Undying "Xu Fu\'s Dimension"',
            'Expiation "Honest Man\'s Death"',
            'Hollow Being "Wu"',
            'Inextinguishable "Phoenix\'s Tail"',
            'Hourai "South Wind, Clear Sky -Fujiyama Volcano-"',
            '"Possessed by Phoenix"',
            '"Hourai Doll"',
            '"Imperishable Shooting"',
            '"Unseasonal Butterfly Storm"',
            '"Blind Nightbird"',
            '"Emperor of the Land of the Rising Sun"',
            '"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)"',
            '"Heaven Spider\'s Butterfly-Capturing Web"',
            '"Tree-Ocean of Hourai"',
            '"Phoenix Rebirth"',
            '"Ancient Duper"',
            '"Total Purification"',
            '"Fantasy Nature"',
            '"Blazing Star"',
            '"Deflation World"',
            '"Matsuyoi-Reflecting Satellite Slash"',
            '"The Phantom of the Grand Guignol"',
            '"Scarlet Destiny"',
            '"Saigyouji Parinirvana"',
            '"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-"',
        ),
        "th13": (
            'Symbol "Dance of the Dead Butterflies"',
            'Symbol "Dance of the Dead Butterflies"',
            'Symbol "Dance of the Dead Butterflies - Cherry Blossoms -"',
            'Symbol "Dance of the Dead Butterflies - Cherry Blossoms -"',
            'Ghostly Butterfly "Ghost Spot"',
            'Ghostly Butterfly "Ghost Spot"',
            'Ghostly Butterfly "Ghost Spot - Cherry Blossoms -"',
            'Ghostly Butterfly "Ghost Spot - Cherry Blossoms -"',
            'Nether Sign "Endless Evening Cherry Blossoms"',
            'Nether Sign "Endless Evening Cherry Blossoms"',
            'Nether Sign "Endless Evening Cherry Blossoms"',
            'Nether Sign "Endless Evening Cherry Blossoms"',
            'Cherry Blossom Sign "Saigyou Cherry Blossom Blizzard"',
            'Cherry Blossom Sign "Saigyou Cherry Blossom Blizzard"',
            'Echo Sign "Mountain Echo"',
            'Echo Sign "Mountain Echo"',
            'Echo Sign "Mountain Echo Scramble"',
            'Echo Sign "Mountain Echo Scramble"',
            'Echo Sign "Power Resonance"',
            'Echo Sign "Power Resonance"',
            'Echo Sign "Power Resonance"',
            'Echo Sign "Power Resonance"',
            'Mountain Echo "Long-Range Echo"',
            'Mountain Echo "Long-Range Echo"',
            'Mountain Echo "Amplify Echo"',
            'Mountain Echo "Amplify Echo"',
            'Great Voice "Charged Cry"',
            'Great Voice "Charged Cry"',
            'Great Voice "Charged Yahoo!"',
            'Great Voice "Charged Yahoo!"',
            'Rainbow Sign "Umbrella Cyclone"',
            'Rainbow Sign "Umbrella Cyclone"',
            'Recovery "Heal By Desire"',
            'Recovery "Heal By Desire"',
            'Recovery "Heal By Desire"',
            'Recovery "Heal By Desire"',
            'Poison Nail "Poison Raze"',
            'Poison Nail "Poison Raze"',
            'Poison Nail "Poison Murder"',
            'Poison Nail "Poison Murder"',
            'Desire Sign "Saved Up Desire Spirit Invitation"',
            'Desire Sign "Saved Up Desire Spirit Invitation"',
            'Desire Spirit "Score Desire Eater"',
            'Desire Spirit "Score Desire Eater"',
            'Evil Sign "Yǎng Xiǎoguǐ"',
            'Evil Sign "Gūhún Yěguǐ"',
            'Evil Sign "Gūhún Yěguǐ"',
            'Demonify "Zǒuhuǒ Rùmó"',
            'Demonify "Zǒuhuǒ Rùmó"',
            'Demonify "Zǒuhuǒ Rùmó"',
            'Demonify "Zǒuhuǒ Rùmó"',
            'Possession "Corpse Tóngjī"',
            'Possession "Corpse Tóngjī"',
            'Spirit Link "Tōnglíng Yoshika"',
            'Spirit Link "Tōnglíng Yoshika"',
            'Taoist Sign "Tao Fetal Movement"',
            'Taoist Sign "Tao Fetal Movement"',
            'Taoist Sign "Tao Fetal Movement"',
            'Taoist Sign "Tao Fetal Movement"',
            'Thunder Arrow "Gagouji\'s Cyclone"',
            'Thunder Arrow "Gagouji\'s Cyclone"',
            'Thunder Arrow "Gagouji\'s Tornado"',
            'Heaven Sign "Rainy Iwafune"',
            'Heaven Sign "Rainy Iwafune"',
            'Heaven Sign "Ame-no-Iwafune, Ascend to Heaven"',
            'Heaven Sign "Ame-no-Iwafune, Ascend to Heaven"',
            'Throwing Dishes "Mononobe\'s Eighty Saké Cups"',
            'Throwing Dishes "Mononobe\'s Eighty Saké Cups"',
            'Throwing Dishes "Mononobe\'s Eighty Saké Cups"',
            'Throwing Dishes "Mononobe\'s Eighty Saké Cups"',
            'Blaze Sign "Blazing Winds of Haibutsu"',
            'Blaze Sign "Blazing Winds of Haibutsu"',
            'Blaze Sign "Sakurai-ji in Flames"',
            'Blaze Sign "Sakurai-ji in Flames"',
            'Saint Girl "Oomonoimi\'s Dinner"',
            'Saint Girl "Oomonoimi\'s Dinner"',
            'Saint Girl "Oomonoimi\'s Dinner"',
            'Saint Girl "Oomonoimi\'s Dinner"',
            'Honor "Colors of Twelve Levels"',
            'Honor "Colors of Twelve Levels"',
            'Honor "Ranks of Twelve Levels"',
            'Honor "Ranks of Twelve Levels"',
            'Hermit Sign "Taoist of the Land of the Rising Sun"',
            'Hermit Sign "Taoist of the Land of the Rising Sun"',
            'Hermit Sign "Emperor of the Land of the Rising Sun"',
            'Hermit Sign "Emperor of the Land of the Rising Sun"',
            'Summon "Royal Clan\'s Chaotic Dance"',
            'Summon "Royal Clan\'s Chaotic Dance"',
            'Summon "Royal Clan\'s Chaotic Dance"',
            'Summon "Royal Clan\'s Chaotic Dance"',
            'Secret Treasure "Armillary Sphere of Ikaruga-dera"',
            'Secret Treasure "Armillary Sphere of Ikaruga-dera"',
            'Secret Treasure "Armillary Sphere of Ikaruga-dera"',
            'Secret Treasure "Prince Shotoku\'s Out-of-Place Artifact"',
            'Light Sign "Halo of the Guse Kannon"',
            'Light Sign "Halo of the Guse Kannon"',
            'Light Sign "Guse Flash"',
            'Light Sign "Guse Flash"',
            'Discernment "Lasers of Seventeen Articles"',
            'Discernment "Lasers of Seventeen Articles"',
            'Divine Light "Honor the Avoidance of Defiance"',
            'Divine Light "Honor the Avoidance of Defiance"',
            '"Falling Stars on Divine Spirit Mausoleum"',
            '"Falling Stars on Divine Spirit Mausoleum"',
            '"Newborn Divine Spirits"',
            '"Newborn Divine Spirits"',
            'Unknown "Will-o\'-wisps in Unknown Orbit"',
            'Unknown "Skyfish with Unknown Shape"',
            'Unknown "Youkai Orb of Unknown Mechanics"',
            'First Duel "Primate Danmaku Transformation"',
            'Second Duel "Carnivorous Danmaku Transformation"',
            'Third Duel "Avian Danmaku Transformation"',
            'Fourth Duel "Amphibian Danmaku Transformation"',
            'Fifth Duel "Scrolls of Frolicking Animals"',
            'Sixth Duel "Tanuki\'s Monstrous School"',
            'Seventh Duel "Wild Deserted Island"',
            'Transformation "Pseudo-Exorcism of the Stupid Shrine Maiden"',
            '"Mamizou Danmaku in Ten Transformations"',
            'Raccoon Sign "Full Moon Pompokolin"',
            'Cherry Blossom Sign "Cherry Blossom Blizzard Hell"',
            'Mountain Echo "Yamabiko\'s Specialty Echo Demonstration"',
            'Poison Nail "Undead Murderer"',
            'Taoist Sign "TAO Fetal Movement ~Dao~"',
            'Vengeful Spirit "Iruka\'s Thunder"',
            'Saint Girl "Sun Goddess\'s Sacrifice"',
            '"Divine Spirits\' Universe"',
            '"Wild Carpet"',
        ),
        "th14": (
            'Ice Sign "Ultimate Blizzard"',
            'Ice Sign "Ultimate Blizzard"',
            'Water Sign "Tail Fin Slap"',
            'Water Sign "Tail Fin Slap"',
            'Water Sign "Tail Fin Slap"',
            'Water Sign "Tail Fin Slap"',
            'Scale Sign "Scale Wave"',
            'Scale Sign "Scale Wave"',
            'Scale Sign "Raging Waves of the Reversed Scale"',
            'Scale Sign "Great Raging Waves of the Reversed Scale"',
            'Flight Sign "Flying Head"',
            'Flight Sign "Flying Head"',
            'Flight Sign "Flying Head"',
            'Flight Sign "Flying Head"',
            'Neck Sign "Close-Eye Shot"',
            'Neck Sign "Close-Eye Shot"',
            'Neck Sign "Rokurokubi Flight"',
            'Neck Sign "Rokurokubi Flight"',
            'Flying Head "Multiplicative Head"',
            'Flying Head "Multiplicative Head"',
            'Flying Head "Seventh Head"',
            'Flying Head "Ninth Head"',
            'Flying Head "Dullahan Night"',
            'Flying Head "Dullahan Night"',
            'Flying Head "Dullahan Night"',
            'Flying Head "Dullahan Night"',
            'Fang Sign "Moonlit Canine Teeth"',
            'Fang Sign "Moonlit Canine Teeth"',
            'Transformation "Triangle Fang"',
            'Transformation "Triangle Fang"',
            'Transformation "Star Fang"',
            'Transformation "Star Fang"',
            'Roar "Strange Roar"',
            'Roar "Strange Roar"',
            'Roar "Full Moon Howling"',
            'Roar "Full Moon Howling"',
            'Wolf Sign "Star Ring Pounce"',
            'Wolf Sign "Star Ring Pounce"',
            'Sirius "High-Speed Pounce"',
            'Sirius "High-Speed Pounce"',
            'Heikyoku "Sounds of Jetavana\'s Bell"',
            'Heikyoku "Sounds of Jetavana\'s Bell"',
            'Heikyoku "Sounds of Jetavana\'s Bell"',
            'Heikyoku "Sounds of Jetavana\'s Bell"',
            'Vengeful Spirit "Hoichi the Earless"',
            'Vengeful Spirit "Hoichi the Earless"',
            'Vengeful Spirit "Great Vengeful Spirit of Taira"',
            'Vengeful Spirit "Great Vengeful Spirit of Taira"',
            'Music Sign "Wicked Musical Score"',
            'Music Sign "Wicked Musical Score"',
            'Music Sign "Malicious Musical Score"',
            'Music Sign "Double Score"',
            'Koto Sign "Sounds of Anicca\'s Koto"',
            'Koto Sign "Sounds of Anicca\'s Koto"',
            'Koto Sign "Sounds of Anicca\'s Koto"',
            'Koto Sign "Sounds of Anicca\'s Koto"',
            'Echo Sign "Heian\'s Reverberation"',
            'Echo Sign "Heian\'s Reverberation"',
            'Echo Sign "Echo Chamber"',
            'Echo Sign "Echo Chamber"',
            'Koto Music "Social Upheaval Koto Music Complement"',
            'Koto Music "Social Upheaval Koto Music Complement"',
            'Koto Music "Social Upheaval Requiem"',
            'Koto Music "Social Upheaval Requiem"',
            'Deceit Sign "Reverse Needle Attack"',
            'Deceit Sign "Reverse Needle Attack"',
            'Deceit Sign "Reverse Needle Attack"',
            'Deceit Sign "Reverse Needle Attack"',
            'Reverse Sign "Danmaku Through the Looking-Glass"',
            'Reverse Sign "Danmaku Through the Looking-Glass"',
            'Reverse Sign "Evil in the Mirror"',
            'Reverse Sign "Evil in the Mirror"',
            'Reverse Sign "This Side Down"',
            'Reverse Sign "This Side Down"',
            'Reverse Sign "Overturning All Under Heaven"',
            'Reverse Sign "Overturning All Under Heaven"',
            'Reverse Bow "Dream Bow of Heaven & Earth"',
            'Reverse Bow "Dream Bow of Heaven & Earth"',
            'Reverse Bow "Decree of the Dream Bow of Heaven & Earth"',
            'Reverse Bow "Decree of the Dream Bow of Heaven & Earth"',
            'Turnabout "Reverse Hierarchy"',
            'Turnabout "Reverse Hierarchy"',
            'Turnabout "Change Air Brave"',
            'Turnabout "Change Air Brave"',
            'Small Barrage "Inchling\'s Path"',
            'Small Barrage "Inchling\'s Path"',
            'Small Barrage "Inchling\'s Thorny Path"',
            'Small Barrage "Inchling\'s Thorny Path"',
            'Mallet "Grow Bigger!"',
            'Mallet "Grow Bigger!"',
            'Mallet "Grow Even Bigger!"',
            'Mallet "Grow Even Bigger!"',
            'Bewitched Sword "Shining Needle Sword"',
            'Bewitched Sword "Shining Needle Sword"',
            'Bewitched Sword "Shining Needle Sword"',
            'Bewitched Sword "Shining Needle Sword"',
            'Mallet "You Grow Bigger!"',
            'Mallet "You Grow Bigger!"',
            'Mallet "You Grow Bigger!"',
            'Mallet "You Grow Bigger!"',
            '"Attack on Dwarf"',
            '"Attack on Dwarf"',
            '"Wall of Issun"',
            '"Wall of Issun"',
            '"Hop-o\'-My-Thumb Seven"',
            '"Hop-o\'-My-Thumb Seven"',
            '"The Seven Issun-Boshi"',
            '"The Seven Issun-Boshi"',
            'String Music "Storm Ensemble"',
            'String Music "Joururi World"',
            'First Drum "Raging Temple Taiko"',
            'Second Drum "Vengeful Spirit Aya-no-Tsuzumi"',
            'Third Drum "Three Strikes at Midnight"',
            'Death Drum "Land Percuss"',
            'Fifth Drum "Den-Den Daiko"',
            'Sixth Drum "Alternate Sticking"',
            'Seventh Drum "High Speed Taiko Rocket"',
            'Eighth Drum "Thunder God\'s Anger"',
            '"Blue Lady Show"',
            '"Pristine Beat"',
        ),
        "th16": (
            'Butterfly Sign "Minute Scales"',
            'Butterfly Sign "Minute Scales"',
            'Butterfly Sign "Swallowtail\'s Scales"',
            'Butterfly Sign "Swallowtail\'s Scales"',
            'Butterfly Sign "Fluttering Summer"',
            'Butterfly Sign "Fluttering Summer"',
            'Butterfly Sign "Midsummer Wingbeats"',
            'Butterfly Sign "Midsummer Wingbeats"',
            'Rain Sign "Imprisoning Autumn Rain"',
            'Rain Sign "Imprisoning Autumn Rain"',
            'Rain Sign "Cursed Torrential Rain"',
            'Rain Sign "Cursed Torrential Rain"',
            'Blade Sign "Yamanba\'s Kitchen Knife Sharpening"',
            'Blade Sign "Yamanba\'s Kitchen Knife Sharpening"',
            'Blade Sign "Yamanba\'s Oni Kitchen Knife Sharpening"',
            'Blade Sign "Yamanba\'s Oni Kitchen Knife Sharpening"',
            'Blade Exhaustion Sign "Mountain Murder"',
            'Blade Exhaustion Sign "Mountain Murder"',
            'Blade Exhaustion Sign "Bloody Mountain Murder"',
            'Blade Exhaustion Sign "Bloody Mountain Murder"',
            'Spring Sign "Surprise Spring"',
            'Spring Sign "Surprise Spring"',
            'Dog Sign "Stray Dog\'s Walk"',
            'Dog Sign "Stray Dog\'s Walk"',
            'Hound Sign "Mountain Hound\'s Walk"',
            'Hound Sign "Mountain Hound\'s Walk"',
            'Spinning Top "Koma-Inu Spin"',
            'Spinning Top "Koma-Inu Spin"',
            'Spinning Top "Koma-Inu Spin"',
            'Spinning Top "Curl Up and Die"',
            'Koma Sign "Solitary A-Um Breathing"',
            'Koma Sign "Solitary A-Um Breathing"',
            'Koma Sign "Solitary A-Um Breathing"',
            'Koma Sign "Solitary A-Um Breathing"',
            'Magic Sign "Instant Bodhi"',
            'Magic Sign "Instant Bodhi"',
            'Magic Sign "Bodhi in an Instant"',
            'Magic Sign "Bodhi in an Instant"',
            'Magic Sign "Bullet Golem"',
            'Magic Sign "Bullet Golem"',
            'Magic Sign "Gigantic Pet Bullet Lifeform"',
            'Magic Sign "Gigantic Pet Bullet Lifeform"',
            'Jizo "Criminal Salvation"',
            'Jizo "Criminal Salvation"',
            'Jizo "Hellfire Salvation"',
            'Jizo "Hellfire Salvation"',
            'Bamboo Sign "Bamboo Spear Dance"',
            'Bamboo Sign "Bamboo Spear Dance"',
            'Bamboo Sign "Bamboo Crazy Dance"',
            'Bamboo Sign "Bamboo Crazy Dance"',
            'Myōga Ginger "Forget Your Name"',
            'Myōga Ginger "Forget Your Name"',
            'Myōga Ginger "Forget Your Name"',
            'Myōga Ginger "Forget Your Name"',
            'Broadleaf Sign "Tanabata Star Festival"',
            'Broadleaf Sign "Tanabata Star Festival"',
            'Broadleaf Sign "Tanabata Star Festival"',
            'Broadleaf Sign "Tanabata Star Festival"',
            'Myōga Blessing "Behind You"',
            'Myōga Blessing "Behind You"',
            'Myōga Blessing "Behind You"',
            'Myōga Blessing "Behind You"',
            'Dance Sign "Behind Festival"',
            'Dance Sign "Behind Festival"',
            'Dance Sign "Behind Festival"',
            'Dance Sign "Behind Festival"',
            'Mad Dance "Tengu-odoshi"',
            'Mad Dance "Tengu-odoshi"',
            'Mad Dance "Frenzied Tengu-Frightening"',
            'Mad Dance "Frenzied Tengu-Frightening"',
            'Back Sign "Halo of the Secret God"',
            'Back Sign "Halo of the Secret God"',
            'Back Sign "Halo of the Secret God"',
            'Back Sign "Halo of the Absolute Secret God"',
            'Hidden Summer "Scorch By Hot Summer"',
            'Hidden Summer "Scorch By Hot Summer"',
            'Hidden Summer "Scorched Earth of Abnormal Intense Heat"',
            'Hidden Summer "Scorched Earth of Abnormal Intense Heat"',
            'Hidden Fall "Die of Famine"',
            'Hidden Fall "Die of Famine"',
            'Hidden Fall "Preta of Abnormal Blight"',
            'Hidden Fall "Preta of Abnormal Blight"',
            'Hidden Winter "Black Snowman"',
            'Hidden Winter "Black Snowman"',
            'Hidden Winter "Snowman of Abnormal Snowfall"',
            'Hidden Winter "Snowman of Abnormal Snowfall"',
            'Hidden Spring "April Wizard"',
            'Hidden Spring "April Wizard"',
            'Hidden Spring "Black Magician of Abnormal Falling Petals"',
            'Hidden Spring "Black Magician of Abnormal Falling Petals"',
            '"Hidden Breezy Cherry Blossom"',
            '"Hidden Breezy Cherry Blossom"',
            '"Hidden Breezy Cherry Blossom"',
            '"Hidden Breezy Cherry Blossom"',
            '"Hidden Perfect Summer Ice"',
            '"Hidden Perfect Summer Ice"',
            '"Hidden Perfect Summer Ice"',
            '"Hidden Perfect Summer Ice"',
            '"Hidden Crazy Fall Wind"',
            '"Hidden Crazy Fall Wind"',
            '"Hidden Crazy Fall Wind"',
            '"Hidden Crazy Fall Wind"',
            '"Hidden Extreme Winter"',
            '"Hidden Extreme Winter"',
            '"Hidden Extreme Winter"',
            '"Hidden Extreme Winter"',
            'Drum Dance "Powerful Cheers"',
            'Mad Dance "Crazy Backup Dance"',
            'Bullet Dance "Twin Typhoons"',
            'Secret Ceremony "Reverse Invoker"',
            'Secret Ceremony "Rear Shots of Betrayal"',
            'Secret Ceremony "Danmaku Dupion"',
            'Secret Ceremony "Fire of Ena"',
            'Secret Ceremony "Kyōgen of the Back Door"',
            'Secret Ceremony "Matarah Dukkha"',
            'Secret Ceremony "Sword of the Seven Stars"',
            'Secret Ceremony "Performers Unattached to Society"',
            '"The Back Face\'s Dark Sarugaku"',
            '"Anarchy Bullet Hell"',
        ),
        "th17": (
            'Stone Sign "Stone Woods"',
            'Stone Sign "Stone Woods"',
            'Stone Sign "Stone Conifers"',
            'Stone Sign "Stone Conifers"',
            'Stone Sign "Children\'s Limbo"',
            'Stone Sign "Children\'s Limbo"',
            'Stone Sign "Adult Children\'s Limbo"',
            'Stone Sign "Adult Children\'s Limbo"',
            'Stone Sign "Stone Baby"',
            'Stone Sign "Stone Baby"',
            'Stone Sign "Heavy Stone Baby"',
            'Stone Sign "Heavy Stone Baby"',
            'Drowning Sign "Drowning in the Sanzu"',
            'Drowning Sign "Drowning in the Sanzu"',
            'Drowning Sign "Drowning in the Sanzu"',
            'Drowning Sign "Drowning in the Sanzu"',
            'Oni Sign "Demon Siege"',
            'Oni Sign "Demon Siege"',
            'Oni Sign "Hungry Demon Siege"',
            'Oni Sign "Hungry Demon Siege"',
            'Water Sign "Ordeal of Water Distribution"',
            'Water Sign "Ordeal of Water Distribution"',
            'Water Sign "High-Level Purgatordeal of Water Distribution"',
            'Water Sign "Ultimate Purgatordeal of Water Distribution"',
            'Light Sign "Ordeal of Surveying"',
            'Light Sign "Ordeal of Surveying"',
            'Light Sign "High-Level Purgatordeal of Surveying"',
            'Light Sign "Ultimate Purgatordeal of Surveying"',
            'Oni Sign "Purgatordeal of Oniwatari"',
            'Oni Sign "Purgatordeal of Oniwatari"',
            'Oni Sign "High-Level Purgatordeal of Oniwatari"',
            'Oni Sign "Hell-Level Purgatordeal of Oniwatari"',
            'Tortoise Sign "Tortoiseshell Hell"',
            'Tortoise Sign "Tortoiseshell Hell"',
            'Tortoise Sign "Tortoiseshell Hell"',
            'Tortoise Sign "Tortoiseshell Hell"',
            'Oni Sign "Beasts Attacking from the Rear"',
            'Oni Sign "Beasts Attacking from the Rear"',
            'Oni Sign "Mangy Beasts Attacking from the Rear"',
            'Oni Sign "Devilish Beasts Attacking from the Rear"',
            'Dragon Sign "Dragon Crest Bullets"',
            'Dragon Sign "Dragon Crest Bullets"',
            'Dragon Sign "Dragon Crest Bullets"',
            'Dragon Sign "Dragon Crest Bullets"',
            'Haniwa "Archer Haniwa"',
            'Haniwa "Archer Haniwa"',
            'Haniwa "Skilled Archer Haniwa"',
            'Haniwa "Skilled Archer Haniwa"',
            'Haniwa "Fencer Haniwa"',
            'Haniwa "Fencer Haniwa"',
            'Haniwa "Skilled Fencer Haniwa"',
            'Haniwa "Skilled Fencer Haniwa"',
            'Haniwa "Cavalry Haniwa"',
            'Haniwa "Cavalry Haniwa"',
            'Haniwa "Skilled Cavalry Haniwa"',
            'Haniwa "Skilled Cavalry Haniwa"',
            'Haniwa "Hollow Inexhaustible Troops"',
            'Haniwa "Hollow Inexhaustible Troops"',
            'Haniwa "Undefeated Inexhaustible Troops"',
            'Haniwa "Undefeated Inexhaustible Troops"',
            'Square Shape "Square-Shaped Sculpting Art"',
            'Square Shape "Square-Shaped Sculpting Art"',
            'Square Shape "Square Creature"',
            'Square Shape "Square Creature"',
            'Circular Shape "Perfect Circle Sculpting Art"',
            'Circular Shape "Perfect Circle Sculpting Art"',
            'Circular Shape "Circle Creature"',
            'Circular Shape "Circle Creature"',
            'Linear Shape "Line-Shaped Sculpting Art"',
            'Linear Shape "Line-Shaped Sculpting Art"',
            'Linear Shape "Linear Creature"',
            'Linear Shape "Linear Creature"',
            'Haniwa "Horse-and-Rider Idol Sculpting Art"',
            'Haniwa "Horse-and-Rider Idol Sculpting Art"',
            'Haniwa "Idol Creature"',
            'Haniwa "Idol Creature"',
            '"Oni-Shaped Sculpting Art"',
            '"Oni-Shaped Sculpting Art"',
            '"Oni-Shaped Sculpting Art"',
            '"Oni-Shaped Sculpting Art"',
            '"Geometric Creature"',
            '"Geometric Creature"',
            '"Geometric Creature"',
            '"Geometric Creature"',
            '"Idola Diabolus"',
            '"Idola Diabolus"',
            '"Idola Diabolus"',
            '"Idola Diabolus"',
            'Bloody Battle "Watershed of Blood"',
            'Bloody Battle "Hell Realm Sight-Line"',
            'Bloody Battle "All-Spirit Oniwatari"',
            'Agile Skill "Thrilling Shot"',
            'Agile Skill "Lightning Neigh"',
            'Agile Skill "Dense Crowd"',
            'Agile Skill "Beast Epidemicity"',
            'Agile Skill "Triangle Chase"',
            'Agile Skill "Black Pegasus Meteor Shot"',
            'Agile Skill "Muscle Explosion"',
            '"Follow Me, Unafraid"',
            '"Oni-Shaped Hoi Polloi"',
            '"Deeds of Devilish Beasts"',
        ),
        "th18": (
            'Beckon Sign "Danmaku Business Boom"',
            'Beckon Sign "Danmaku Business Boom"',
            'Beckon Sign "Danmaku Business Boom"',
            'Beckon Sign "Danmaku Business Boom"',
            'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"',
            'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"',
            'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"',
            'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"',
            'Forest Sign "Tree-Veiling Technology"',
            'Forest Sign "Tree-Veiling Technology"',
            'Forest Sign "Extreme Tree-Veiling Technology"',
            'Forest Sign "True Tree-Veiling Technology"',
            'Forest Sign "Innermost Forest Region"',
            'Forest Sign "Innermost Forest Region"',
            'Forest Sign "Extreme Innermost Forest Region"',
            'Forest Sign "True Innermost Forest Region"',
            'Leaf Skill "Green Spiral"',
            'Leaf Skill "Green Spiral"',
            'Leaf Skill "Green Cyclone"',
            'Leaf Skill "Green Tornado"',
            'Mountain Sign "Heaven-Shaking Kumomagusa"',
            'Mountain Sign "Heaven-Shaking Kumomagusa"',
            'Mountain Apparition "Astonishing Kumomagusa"',
            'Mountain Apparition "Astonishing Kumomagusa"',
            'Mountain Sign "Usuyukisou Shining with Bewitching Light"',
            'Mountain Sign "Usuyukisou Shining with Bewitching Light"',
            'Mountain Apparition "Usuyukisou of Thronging Crowds of Youma"',
            'Mountain Apparition "Usuyukisou of Thronging Crowds of Youma"',
            'Mountain Flower "Komakusa of Massacre"',
            'Mountain Flower "Komakusa of Massacre"',
            'Mountain Flower "Mountain Queen of Massacre"',
            'Mountain Flower "Mountain Queen of Massacre"',
            'Orb Sign "Rainbow Dragon Yin-Yang Orbs"',
            'Orb Sign "Rainbow Dragon Yin-Yang Orbs"',
            'Orb Sign "Rainbow Dragon Yin-Yang Orbs"',
            'Orb Sign "Yin-Yang Divine Orbs"',
            'Jeweled General "Queen of Yin-Yang Sphere"',
            'Jeweled General "Queen of Yin-Yang Sphere"',
            'Queenly Gem "Beyond the Rainbow Door"',
            'Queenly Gem "Beyond the Rainbow Door"',
            '"Yin-Yang Suffocation"',
            '"Yin-Yang Suffocation"',
            '"Yin-Yang Suffocation"',
            '"Yin-Yang Suffocation"',
            'Calamitous Star "Dance of Star-Sparked Wildfire"',
            'Calamitous Star "Dance of Star-Sparked Wildfire"',
            'Calamitous Star "Wild Dance of Star-Sparked Wildfire"',
            'Calamitous Star "Wild Dance of Star-Sparked Wildfire"',
            'Stellar Wind "Dance of Dazzling Iridescence"',
            'Stellar Wind "Dance of Dazzling Iridescence"',
            'Stellar Wind "Wild Dance of Dazzling Iridescence"',
            'Stellar Wind "Wild Dance of Dazzling Iridescence"',
            'Luminous Horse "Dance of Sky-Racing Heavenly Steeds"',
            'Luminous Horse "Dance of Sky-Racing Heavenly Steeds"',
            'Luminous Horse "Wild Dance of Sky-Racing Heavenly Steeds"',
            'Luminous Horse "Wild Dance of Sky-Racing Heavenly Steeds"',
            'Rainbow Illumination "Clear and Tranquil Wind and Moon"',
            'Rainbow Illumination "Clear and Tranquil Wind and Moon"',
            'Rainbow Illumination "Clear and Tranquil Wind and Moon"',
            'Rainbow Illumination "Clear and Tranquil Wind and Moon"',
            '"An Offering to the Ownerless"',
            '"An Offering to the Ownerless"',
            '"An Offering to the Ownerless"',
            '"An Offering to the Ownerless"',
            '"Danmaku Hoarder\'s Obsession"',
            '"Danmaku Hoarder\'s Obsession"',
            '"Danmaku Hoarder\'s Obsession"',
            '"Danmaku Hoarder\'s Obsession"',
            '"Bullet Market"',
            '"Bullet Market"',
            '"High Density Bullet Market"',
            '"Danmaku Free Market"',
            '"Rainbow Ring of People"',
            '"Rainbow Ring of People"',
            '"Rainbow Ring of People"',
            '"Rainbow Ring of People"',
            '"Bullet Dominion"',
            '"Bullet Dominion"',
            '"Tyrannical Bullet Dominion"',
            '"Inhumane Bullet Dominion"',
            '"Asylum of Danmaku"',
            '"Asylum of Danmaku"',
            '"Asylum of Danmaku"',
            '"Asylum of Danmaku"',
            'Fox Sign "Fox Winder"',
            'Kuda-gitsune "Cylinder Fox"',
            'Stellar Fox "Dance of Heavenly Foxes and Dragon Stars"',
            'Kodoku "Cannibalistic Insect"',
            'Kodoku "Cave Swarmer"',
            'Kodoku "Sky Pendra"',
            'Mining "Ever-Accumulating Mine Dump"',
            'Mining "Mine Blast"',
            'Mining "Shield Method of the Youkai"',
            'Oomukade "Snake Eater"',
            'Oomukade "Dragon Eater"',
            '"Kodoku Gourmet"',
            '"Mushihime-sama\'s Resplendent and Restless Daily Life"',
        ),
    }
)

spell_names_jp = immutabledict(
    {
        "th08": (
            "蛍符「地上の流星」",
            "蛍符「地上の彗星」",
            "灯符「ファイヤフライフェノメノン」",
            "灯符「ファイヤフライフェノメノン」",
            "灯符「ファイヤフライフェノメノン」",
            "灯符「ファイヤフライフェノメノン」",
            "蠢符「リトルバグ」",
            "蠢符「リトルバグストーム」",
            "蠢符「ナイトバグストーム」",
            "蠢符「ナイトバグトルネード」",
            "隠蟲「永夜蟄居」",
            "隠蟲「永夜蟄居」",
            "隠蟲「永夜蟄居」",
            "声符「梟の夜鳴声」",
            "声符「梟の夜鳴声」",
            "声符「木菟咆哮」",
            "声符「木菟咆哮」",
            "蛾符「天蛾の蠱道」",
            "蛾符「天蛾の蠱道」",
            "毒符「毒蛾の鱗粉」",
            "猛毒「毒蛾の暗闇演舞」",
            "鷹符「イルスタードダイブ」",
            "鷹符「イルスタードダイブ」",
            "鷹符「イルスタードダイブ」",
            "鷹符「イルスタードダイブ」",
            "夜盲「夜雀の歌」",
            "夜盲「夜雀の歌」",
            "夜盲「夜雀の歌」",
            "夜盲「夜雀の歌」",
            "夜雀「真夜中のコーラスマスター」",
            "夜雀「真夜中のコーラスマスター」",
            "夜雀「真夜中のコーラスマスター」",
            "産霊「ファーストピラミッド」",
            "産霊「ファーストピラミッド」",
            "産霊「ファーストピラミッド」",
            "産霊「ファーストピラミッド」",
            "始符「エフェメラリティ137」",
            "始符「エフェメラリティ137」",
            "始符「エフェメラリティ137」",
            "野符「武烈クライシス」",
            "野符「将門クライシス」",
            "野符「義満クライシス」",
            "野符「GHQクライシス」",
            "国符「三種の神器　剣」",
            "国符「三種の神器　玉」",
            "国符「三種の神器　鏡」",
            "国体「三種の神器　郷」",
            "終符「幻想天皇」",
            "終符「幻想天皇」",
            "虚史「幻想郷伝説」",
            "虚史「幻想郷伝説」",
            "未来「高天原」",
            "未来「高天原」",
            "未来「高天原」",
            "夢符「二重結界」",
            "夢符「二重結界」",
            "夢境「二重大結界」",
            "夢境「二重大結界」",
            "霊符「夢想封印　散」",
            "霊符「夢想封印　散」",
            "散霊「夢想封印　寂」",
            "散霊「夢想封印　寂」",
            "夢符「封魔陣」",
            "夢符「封魔陣」",
            "神技「八方鬼縛陣」",
            "神技「八方龍殺陣」",
            "霊符「夢想封印　集」",
            "霊符「夢想封印　集」",
            "回霊「夢想封印　侘」",
            "回霊「夢想封印　侘」",
            "境界「二重弾幕結界」",
            "境界「二重弾幕結界」",
            "大結界「博麗弾幕結界」",
            "大結界「博麗弾幕結界」",
            "神霊「夢想封印　瞬」",
            "神霊「夢想封印　瞬」",
            "神霊「夢想封印　瞬」",
            "魔符「ミルキーウェイ」",
            "魔符「ミルキーウェイ」",
            "魔空「アステロイドベルト」",
            "魔空「アステロイドベルト」",
            "魔符「スターダストレヴァリエ」",
            "魔符「スターダストレヴァリエ」",
            "黒魔「イベントホライズン」",
            "黒魔「イベントホライズン」",
            "恋符「ノンディレクショナルレーザー」",
            "恋符「ノンディレクショナルレーザー」",
            "恋風「スターライトタイフーン」",
            "恋風「スターライトタイフーン」",
            "恋符「マスタースパーク」",
            "恋符「マスタースパーク」",
            "恋心「ダブルスパーク」",
            "恋心「ダブルスパーク」",
            "光符「アースライトレイ」",
            "光符「アースライトレイ」",
            "光撃「シュート・ザ・ムーン」",
            "光撃「シュート・ザ・ムーン」",
            "魔砲「ファイナルスパーク」",
            "魔砲「ファイナルスパーク」",
            "魔砲「ファイナルマスタースパーク」",
            "波符「赤眼催眠(マインドシェイカー)」",
            "波符「赤眼催眠(マインドシェイカー)」",
            "幻波「赤眼催眠(マインドブローイング)」",
            "幻波「赤眼催眠(マインドブローイング)」",
            "狂符「幻視調律(ビジョナリチューニング)」",
            "狂符「幻視調律(ビジョナリチューニング)」",
            "狂視「狂視調律(イリュージョンシーカー)」",
            "狂視「狂視調律(イリュージョンシーカー)」",
            "懶符「生神停止(アイドリングウェーブ)」",
            "懶符「生神停止(アイドリングウェーブ)」",
            "懶惰「生神停止(マインドストッパー)」",
            "懶惰「生神停止(マインドストッパー)」",
            "散符「真実の月(インビジブルフルムーン)」",
            "散符「真実の月(インビジブルフルムーン)」",
            "散符「真実の月(インビジブルフルムーン)」",
            "散符「真実の月(インビジブルフルムーン)」",
            "月眼「月兎遠隔催眠術(テレメスメリズム)」",
            "月眼「月兎遠隔催眠術(テレメスメリズム)」",
            "月眼「月兎遠隔催眠術(テレメスメリズム)」",
            "天丸「壺中の天地」",
            "天丸「壺中の天地」",
            "天丸「壺中の天地」",
            "天丸「壺中の天地」",
            "覚神「神代の記憶」",
            "覚神「神代の記憶」",
            "神符「天人の系譜」",
            "神符「天人の系譜」",
            "蘇活「生命遊戯　-ライフゲーム-」",
            "蘇活「生命遊戯　-ライフゲーム-」",
            "蘇生「ライジングゲーム」",
            "蘇生「ライジングゲーム」",
            "操神「オモイカネディバイス」",
            "操神「オモイカネディバイス」",
            "神脳「オモイカネブレイン」",
            "神脳「オモイカネブレイン」",
            "天呪「アポロ１３」",
            "天呪「アポロ１３」",
            "天呪「アポロ１３」",
            "天呪「アポロ１３」",
            "秘術「天文密葬法」",
            "秘術「天文密葬法」",
            "秘術「天文密葬法」",
            "秘術「天文密葬法」",
            "禁薬「蓬莱の薬」",
            "禁薬「蓬莱の薬」",
            "禁薬「蓬莱の薬」",
            "禁薬「蓬莱の薬」",
            "薬符「壺中の大銀河」",
            "薬符「壺中の大銀河」",
            "薬符「壺中の大銀河」",
            "薬符「壺中の大銀河」",
            "難題「龍の頸の玉 -五色の弾丸-」",
            "難題「龍の頸の玉 -五色の弾丸-」",
            "神宝「ブリリアントドラゴンバレッタ」",
            "神宝「ブリリアントドラゴンバレッタ」",
            "難題「仏の御石の鉢 -砕けぬ意思-」",
            "難題「仏の御石の鉢 -砕けぬ意思-」",
            "神宝「ブディストダイアモンド」",
            "神宝「ブディストダイアモンド」",
            "難題「火鼠の皮衣 -焦れぬ心-」",
            "難題「火鼠の皮衣 -焦れぬ心-」",
            "神宝「サラマンダーシールド」",
            "神宝「サラマンダーシールド」",
            "難題「燕の子安貝 -永命線-」",
            "難題「燕の子安貝 -永命線-」",
            "神宝「ライフスプリングインフィニティ」",
            "神宝「ライフスプリングインフィニティ」",
            "難題「蓬莱の弾の枝 -虹色の弾幕-」",
            "難題「蓬莱の弾の枝 -虹色の弾幕-」",
            "神宝「蓬莱の玉の枝 -夢色の郷-」",
            "神宝「蓬莱の玉の枝 -夢色の郷-」",
            "「永夜返し -初月-」",
            "「永夜返し -三日月-」",
            "「永夜返し -上つ弓張-」",
            "「永夜返し -待宵-」",
            "「永夜返し -子の刻-」",
            "「永夜返し -子の二つ-」",
            "「永夜返し -子の三つ-」",
            "「永夜返し -子の四つ-」",
            "「永夜返し -丑の刻-」",
            "「永夜返し -丑の二つ-」",
            "「永夜返し -丑三つ時-」",
            "「永夜返し -丑の四つ-」",
            "「永夜返し -寅の刻-」",
            "「永夜返し -寅の二つ-」",
            "「永夜返し -寅の三つ-」",
            "「永夜返し -寅の四つ-」",
            "「永夜返し -朝靄-」",
            "「永夜返し -夜明け-」",
            "「永夜返し -明けの明星-」",
            "「永夜返し -世明け-」",
            "旧史「旧秘境史　-オールドヒストリー-」",
            "転世「一条戻り橋」",
            "新史「新幻想史　-ネクストヒストリー-」",
            "時効「月のいはかさの呪い」",
            "不死「火の鳥　-鳳翼天翔-」",
            "藤原「滅罪寺院傷」",
            "不死「徐福時空」",
            "滅罪「正直者の死」",
            "虚人「ウー」",
            "不滅「フェニックスの尾」",
            "蓬莱「凱風快晴　-フジヤマヴォルケイノ-」",
            "「パゼストバイフェニックス」",
            "「蓬莱人形」",
            "「インペリシャブルシューティング」",
            "「季節外れのバタフライストーム」",
            "「ブラインドナイトバード」",
            "「日出づる国の天子」",
            "「幻朧月睨(ルナティックレッドアイズ)」",
            "「天網蜘網捕蝶の法」",
            "「蓬莱の樹海」",
            "「フェニックス再誕」",
            "「エンシェントデューパー」",
            "「無何有浄化」",
            "「夢想天生」",
            "「ブレイジングスター」",
            "「デフレーションワールド」",
            "「待宵反射衛星斬」",
            "「グランギニョル座の怪人」",
            "「スカーレットディスティニー」",
            "「西行寺無余涅槃」",
            "「深弾幕結界　-夢幻泡影-」",
        ),
        "th13": (
            "符牒「死蝶の舞」",
            "符牒「死蝶の舞」",
            "符牒「死蝶の舞　- 桜花 -」",
            "符牒「死蝶の舞　- 桜花 -」",
            "幽蝶「ゴーストスポット」",
            "幽蝶「ゴーストスポット」",
            "幽蝶「ゴーストスポット　- 桜花 -」",
            "幽蝶「ゴーストスポット　- 桜花 -」",
            "冥符「常夜桜」",
            "冥符「常夜桜」",
            "冥符「常夜桜」",
            "冥符「常夜桜」",
            "桜符「西行桜吹雪」",
            "桜符「西行桜吹雪」",
            "響符「マウンテンエコー」",
            "響符「マウンテンエコー」",
            "響符「マウンテンエコースクランブル」",
            "響符「マウンテンエコースクランブル」",
            "響符「パワーレゾナンス」",
            "響符「パワーレゾナンス」",
            "響符「パワーレゾナンス」",
            "響符「パワーレゾナンス」",
            "山彦「ロングレンジエコー」",
            "山彦「ロングレンジエコー」",
            "山彦「アンプリファイエコー」",
            "山彦「アンプリファイエコー」",
            "大声「チャージドクライ」",
            "大声「チャージドクライ」",
            "大声「チャージドヤッホー」",
            "大声「チャージドヤッホー」",
            "虹符「アンブレラサイクロン」",
            "虹符「アンブレラサイクロン」",
            "回復「ヒールバイデザイア」",
            "回復「ヒールバイデザイア」",
            "回復「ヒールバイデザイア」",
            "回復「ヒールバイデザイア」",
            "毒爪「ポイズンレイズ」",
            "毒爪「ポイズンレイズ」",
            "毒爪「ポイズンマーダー」",
            "毒爪「ポイズンマーダー」",
            "欲符「稼欲霊招来」",
            "欲符「稼欲霊招来」",
            "欲霊「スコアデザイアイーター」",
            "欲霊「スコアデザイアイーター」",
            "邪符「ヤンシャオグイ」",
            "邪符「グーフンイエグイ」",
            "邪符「グーフンイエグイ」",
            "入魔「ゾウフォルゥモォ」",
            "入魔「ゾウフォルゥモォ」",
            "入魔「ゾウフォルゥモォ」",
            "入魔「ゾウフォルゥモォ」",
            "降霊「死人タンキー」",
            "降霊「死人タンキー」",
            "通霊「トンリン芳香」",
            "通霊「トンリン芳香」",
            "道符「タオ胎動」",
            "道符「タオ胎動」",
            "道符「タオ胎動」",
            "道符「タオ胎動」",
            "雷矢「ガゴウジサイクロン」",
            "雷矢「ガゴウジサイクロン」",
            "雷矢「ガゴウジトルネード」",
            "天符「雨の磐舟」",
            "天符「雨の磐舟」",
            "天符「天の磐舟よ天へ昇れ」",
            "天符「天の磐舟よ天へ昇れ」",
            "投皿「物部の八十平瓮」",
            "投皿「物部の八十平瓮」",
            "投皿「物部の八十平瓮」",
            "投皿「物部の八十平瓮」",
            "炎符「廃仏の炎風」",
            "炎符「廃仏の炎風」",
            "炎符「桜井寺炎上」",
            "炎符「桜井寺炎上」",
            "聖童女「大物忌正餐」",
            "聖童女「大物忌正餐」",
            "聖童女「大物忌正餐」",
            "聖童女「大物忌正餐」",
            "名誉「十二階の色彩」",
            "名誉「十二階の色彩」",
            "名誉「十二階の冠位」",
            "名誉「十二階の冠位」",
            "仙符「日出ずる処の道士」",
            "仙符「日出ずる処の道士」",
            "仙符「日出ずる処の天子」",
            "仙符「日出ずる処の天子」",
            "召喚「豪族乱舞」",
            "召喚「豪族乱舞」",
            "召喚「豪族乱舞」",
            "召喚「豪族乱舞」",
            "秘宝「斑鳩寺の天球儀」",
            "秘宝「斑鳩寺の天球儀」",
            "秘宝「斑鳩寺の天球儀」",
            "秘宝「聖徳太子のオーパーツ」",
            "光符「救世観音の光後光」",
            "光符「救世観音の光後光」",
            "光符「グセフラッシュ」",
            "光符「グセフラッシュ」",
            "眼光「十七条のレーザー」",
            "眼光「十七条のレーザー」",
            "神光「逆らう事なきを宗とせよ」",
            "神光「逆らう事なきを宗とせよ」",
            "「星降る神霊廟」",
            "「星降る神霊廟」",
            "「生まれたての神霊」",
            "「生まれたての神霊」",
            "アンノウン「軌道不明の鬼火」",
            "アンノウン「姿態不明の空魚」",
            "アンノウン「原理不明の妖怪玉」",
            "壱番勝負「霊長化弾幕変化」",
            "弐番勝負「肉食化弾幕変化」",
            "参番勝負「延羽化弾幕変化」",
            "四番勝負「両生化弾幕変化」",
            "伍番勝負「鳥獣戯画」",
            "六番勝負「狸の化け学校」",
            "七番勝負「野生の離島」",
            "変化「まぬけ巫女の偽調伏」",
            "「マミゾウ化弾幕十変化」",
            "狢符「満月のポンポコリン」",
            "桜符「桜吹雪地獄」",
            "山彦「ヤマビコの本領発揮エコー」",
            "毒爪「死なない殺人鬼」",
            "道符「ＴＡＯ胎動　〜道〜」",
            "怨霊「入鹿の雷」",
            "聖童女「太陽神の贄」",
            "「神霊大宇宙」",
            "「ワイルドカーペット」",
        ),
        "th14": (
            "氷符「アルティメットブリザード」",
            "氷符「アルティメットブリザード」",
            "水符「テイルフィンスラップ」",
            "水符「テイルフィンスラップ」",
            "水符「テイルフィンスラップ」",
            "水符「テイルフィンスラップ」",
            "鱗符「スケールウェイブ」",
            "鱗符「スケールウェイブ」",
            "鱗符「逆鱗の荒波」",
            "鱗符「逆鱗の大荒波」",
            "飛符「フライングヘッド」",
            "飛符「フライングヘッド」",
            "飛符「フライングヘッド」",
            "飛符「フライングヘッド」",
            "首符「クローズアイショット」",
            "首符「クローズアイショット」",
            "首符「ろくろ首飛来」",
            "首符「ろくろ首飛来」",
            "飛頭「マルチプリケイティブヘッド」",
            "飛頭「マルチプリケイティブヘッド」",
            "飛頭「セブンズヘッド」",
            "飛頭「ナインズヘッド」",
            "飛頭「デュラハンナイト」",
            "飛頭「デュラハンナイト」",
            "飛頭「デュラハンナイト」",
            "飛頭「デュラハンナイト」",
            "牙符「月下の犬歯」",
            "牙符「月下の犬歯」",
            "変身「トライアングルファング」",
            "変身「トライアングルファング」",
            "変身「スターファング」",
            "変身「スターファング」",
            "咆哮「ストレンジロア」",
            "咆哮「ストレンジロア」",
            "咆哮「満月の遠吠え」",
            "咆哮「満月の遠吠え」",
            "狼符「スターリングパウンス」",
            "狼符「スターリングパウンス」",
            "天狼「ハイスピードパウンス」",
            "天狼「ハイスピードパウンス」",
            "平曲「祇園精舎の鐘の音」",
            "平曲「祇園精舎の鐘の音」",
            "平曲「祇園精舎の鐘の音」",
            "平曲「祇園精舎の鐘の音」",
            "怨霊「耳無し芳一」",
            "怨霊「耳無し芳一」",
            "怨霊「平家の大怨霊」",
            "怨霊「平家の大怨霊」",
            "楽符「邪悪な五線譜」",
            "楽符「邪悪な五線譜」",
            "楽符「凶悪な五線譜」",
            "楽符「ダブルスコア」",
            "琴符「諸行無常の琴の音」",
            "琴符「諸行無常の琴の音」",
            "琴符「諸行無常の琴の音」",
            "琴符「諸行無常の琴の音」",
            "響符「平安の残響」",
            "響符「平安の残響」",
            "響符「エコーチェンバー」",
            "響符「エコーチェンバー」",
            "箏曲「下克上送箏曲」",
            "箏曲「下克上送箏曲」",
            "箏曲「下克上レクイエム」",
            "箏曲「下克上レクイエム」",
            "欺符「逆針撃」",
            "欺符「逆針撃」",
            "欺符「逆針撃」",
            "欺符「逆針撃」",
            "逆符「鏡の国の弾幕」",
            "逆符「鏡の国の弾幕」",
            "逆符「イビルインザミラー」",
            "逆符「イビルインザミラー」",
            "逆符「天地有用」",
            "逆符「天地有用」",
            "逆符「天下転覆」",
            "逆符「天下転覆」",
            "逆弓「天壌夢弓」",
            "逆弓「天壌夢弓」",
            "逆弓「天壌夢弓の詔勅」",
            "逆弓「天壌夢弓の詔勅」",
            "逆転「リバースヒエラルキー」",
            "逆転「リバースヒエラルキー」",
            "逆転「チェンジエアブレイブ」",
            "逆転「チェンジエアブレイブ」",
            "小弾「小人の道」",
            "小弾「小人の道」",
            "小弾「小人の茨道」",
            "小弾「小人の茨道」",
            "小槌「大きくなあれ」",
            "小槌「大きくなあれ」",
            "小槌「もっと大きくなあれ」",
            "小槌「もっと大きくなあれ」",
            "妖剣「輝針剣」",
            "妖剣「輝針剣」",
            "妖剣「輝針剣」",
            "妖剣「輝針剣」",
            "小槌「お前が大きくなあれ」",
            "小槌「お前が大きくなあれ」",
            "小槌「お前が大きくなあれ」",
            "小槌「お前が大きくなあれ」",
            "「進撃の小人」",
            "「進撃の小人」",
            "「ウォールオブイッスン」",
            "「ウォールオブイッスン」",
            "「ホップオマイサムセブン」",
            "「ホップオマイサムセブン」",
            "「七人の一寸法師」",
            "「七人の一寸法師」",
            "弦楽「嵐のアンサンブル」",
            "弦楽「浄瑠璃世界」",
            "一鼓「暴れ宮太鼓」",
            "二鼓「怨霊アヤノツヅミ」",
            "三鼓「午前零時のスリーストライク」",
            "死鼓「ランドパーカス」",
            "五鼓「デンデン太鼓」",
            "六鼓「オルタネイトスティッキング」",
            "七鼓「高速和太鼓ロケット」",
            "八鼓「雷神の怒り」",
            "「ブルーレディショー」",
            "「プリスティンビート」",
        ),
        "th16": (
            "蝶符「ミニットスケールス」",
            "蝶符「ミニットスケールス」",
            "蝶符「アゲハの鱗粉」",
            "蝶符「アゲハの鱗粉」",
            "蝶符「フラッタリングサマー」",
            "蝶符「フラッタリングサマー」",
            "蝶符「真夏の羽ばたき」",
            "蝶符「真夏の羽ばたき」",
            "雨符「囚われの秋雨」",
            "雨符「囚われの秋雨」",
            "雨符「呪われた柴榑雨」",
            "雨符「呪われた柴榑雨」",
            "刃符「山姥の包丁研ぎ」",
            "刃符「山姥の包丁研ぎ」",
            "刃符「山姥の鬼包丁研ぎ」",
            "刃符「山姥の鬼包丁研ぎ」",
            "尽符「マウンテンマーダー」",
            "尽符「マウンテンマーダー」",
            "尽符「ブラッディマウンテンマーダー」",
            "尽符「ブラッディマウンテンマーダー」",
            "春符「サプライズスプリング」",
            "春符「サプライズスプリング」",
            "犬符「野良犬の散歩」",
            "犬符「野良犬の散歩」",
            "狗符「山狗の散歩」",
            "狗符「山狗の散歩」",
            "独楽「コマ犬回し」",
            "独楽「コマ犬回し」",
            "独楽「コマ犬回し」",
            "独楽「カールアップアンドダイ」",
            "狛符「独り阿吽の呼吸」",
            "狛符「独り阿吽の呼吸」",
            "狛符「独り阿吽の呼吸」",
            "狛符「独り阿吽の呼吸」",
            "魔符「インスタントボーディ」",
            "魔符「インスタントボーディ」",
            "魔符「即席菩提」",
            "魔符「即席菩提」",
            "魔符「バレットゴーレム」",
            "魔符「バレットゴーレム」",
            "魔符「ペットの巨大弾生命体」",
            "魔符「ペットの巨大弾生命体」",
            "地蔵「クリミナルサルヴェイション」",
            "地蔵「クリミナルサルヴェイション」",
            "地蔵「業火救済」",
            "地蔵「業火救済」",
            "竹符「バンブースピアダンス」",
            "竹符「バンブースピアダンス」",
            "竹符「バンブークレイジーダンス」",
            "竹符「バンブークレイジーダンス」",
            "茗荷「フォゲットユアネーム」",
            "茗荷「フォゲットユアネーム」",
            "茗荷「フォゲットユアネーム」",
            "茗荷「フォゲットユアネーム」",
            "笹符「タナバタスターフェスティバル」",
            "笹符「タナバタスターフェスティバル」",
            "笹符「タナバタスターフェスティバル」",
            "笹符「タナバタスターフェスティバル」",
            "冥加「ビハインドユー」",
            "冥加「ビハインドユー」",
            "冥加「ビハインドユー」",
            "冥加「ビハインドユー」",
            "舞符「ビハインドフェスティバル」",
            "舞符「ビハインドフェスティバル」",
            "舞符「ビハインドフェスティバル」",
            "舞符「ビハインドフェスティバル」",
            "狂舞「テングオドシ」",
            "狂舞「テングオドシ」",
            "狂舞「狂乱天狗怖し」",
            "狂舞「狂乱天狗怖し」",
            "後符「秘神の後光」",
            "後符「秘神の後光」",
            "後符「秘神の後光」",
            "後符「絶対秘神の後光」",
            "裏夏「スコーチ・バイ・ホットサマー」",
            "裏夏「スコーチ・バイ・ホットサマー」",
            "裏夏「異常猛暑の焦土」",
            "裏夏「異常猛暑の焦土」",
            "裏秋「ダイ・オブ・ファミン」",
            "裏秋「ダイ・オブ・ファミン」",
            "裏秋「異常枯死の餓鬼」",
            "裏秋「異常枯死の餓鬼」",
            "裏冬「ブラックスノーマン」",
            "裏冬「ブラックスノーマン」",
            "裏冬「異常降雪の雪だるま」",
            "裏冬「異常降雪の雪だるま」",
            "裏春「エイプリルウィザード」",
            "裏春「エイプリルウィザード」",
            "裏春「異常落花の魔術使い」",
            "裏春「異常落花の魔術使い」",
            "「裏・ブリージーチェリーブロッサム」",
            "「裏・ブリージーチェリーブロッサム」",
            "「裏・ブリージーチェリーブロッサム」",
            "「裏・ブリージーチェリーブロッサム」",
            "「裏・パーフェクトサマーアイス」",
            "「裏・パーフェクトサマーアイス」",
            "「裏・パーフェクトサマーアイス」",
            "「裏・パーフェクトサマーアイス」",
            "「裏・クレイジーフォールウィンド」",
            "「裏・クレイジーフォールウィンド」",
            "「裏・クレイジーフォールウィンド」",
            "「裏・クレイジーフォールウィンド」",
            "「裏・エクストリームウィンター」",
            "「裏・エクストリームウィンター」",
            "「裏・エクストリームウィンター」",
            "「裏・エクストリームウィンター」",
            "鼓舞「パワフルチアーズ」",
            "狂舞「クレイジーバックダンス」",
            "弾舞「二つ目の台風」",
            "秘儀「リバースインヴォーカー」",
            "秘儀「裏切りの後方射撃」",
            "秘儀「弾幕の玉繭」",
            "秘儀「穢那の火」",
            "秘儀「後戸の狂言」",
            "秘儀「マターラドゥッカ」",
            "秘儀「七星の剣」",
            "秘儀「無縁の芸能者」",
            "「背面の暗黒猿楽」",
            "「アナーキーバレットヘル」",
        ),
        "th17": (
            "石符「ストーンウッズ」",
            "石符「ストーンウッズ」",
            "石符「ストーンコニファー」",
            "石符「ストーンコニファー」",
            "石符「チルドレンズリンボ」",
            "石符「チルドレンズリンボ」",
            "石符「アダルトチルドレンズリンボ」",
            "石符「アダルトチルドレンズリンボ」",
            "石符「ストーンベイビー」",
            "石符「ストーンベイビー」",
            "石符「ヘビーストーンベイビー」",
            "石符「ヘビーストーンベイビー」",
            "溺符「三途の淪溺」",
            "溺符「三途の淪溺」",
            "溺符「三途の淪溺」",
            "溺符「三途の淪溺」",
            "鬼符「デーモンシージ」",
            "鬼符「デーモンシージ」",
            "鬼符「ハングリーデーモンシージ」",
            "鬼符「ハングリーデーモンシージ」",
            "水符「水配りの試練」",
            "水符「水配りの試練」",
            "水符「水配りの上級試煉」",
            "水符「水配りの極級試煉」",
            "光符「見渡しの試練」",
            "光符「見渡しの試練」",
            "光符「見渡しの上級試煉」",
            "光符「見渡しの極級試煉」",
            "鬼符「鬼渡の試練」",
            "鬼符「鬼渡の試練」",
            "鬼符「鬼渡の上級試煉」",
            "鬼符「鬼渡の獄級試煉」",
            "亀符「亀甲地獄」",
            "亀符「亀甲地獄」",
            "亀符「亀甲地獄」",
            "亀符「亀甲地獄」",
            "鬼符「搦手の畜生」",
            "鬼符「搦手の畜生」",
            "鬼符「搦手の犬畜生」",
            "鬼符「搦手の鬼畜生」",
            "龍符「龍紋弾」",
            "龍符「龍紋弾」",
            "龍符「龍紋弾」",
            "龍符「龍紋弾」",
            "埴輪「弓兵埴輪」",
            "埴輪「弓兵埴輪」",
            "埴輪「熟練弓兵埴輪」",
            "埴輪「熟練弓兵埴輪」",
            "埴輪「剣士埴輪」",
            "埴輪「剣士埴輪」",
            "埴輪「熟練剣士埴輪」",
            "埴輪「熟練剣士埴輪」",
            "埴輪「騎馬兵埴輪」",
            "埴輪「騎馬兵埴輪」",
            "埴輪「熟練騎馬兵埴輪」",
            "埴輪「熟練騎馬兵埴輪」",
            "埴輪「がらんどうの無尽兵団」",
            "埴輪「がらんどうの無尽兵団」",
            "埴輪「不敗の無尽兵団」",
            "埴輪「不敗の無尽兵団」",
            "方形「方形造形術」",
            "方形「方形造形術」",
            "方形「スクエアクリーチャー」",
            "方形「スクエアクリーチャー」",
            "円形「真円造形術」",
            "円形「真円造形術」",
            "円形「サークルクリーチャー」",
            "円形「サークルクリーチャー」",
            "線形「線形造形術」",
            "線形「線形造形術」",
            "線形「リニアクリーチャー」",
            "線形「リニアクリーチャー」",
            "埴輪「偶像人馬造形術」",
            "埴輪「偶像人馬造形術」",
            "埴輪「アイドルクリーチャー」",
            "埴輪「アイドルクリーチャー」",
            "「鬼形造形術」",
            "「鬼形造形術」",
            "「鬼形造形術」",
            "「鬼形造形術」",
            "「ジオメトリッククリーチャー」",
            "「ジオメトリッククリーチャー」",
            "「ジオメトリッククリーチャー」",
            "「ジオメトリッククリーチャー」",
            "「イドラディアボルス」",
            "「イドラディアボルス」",
            "「イドラディアボルス」",
            "「イドラディアボルス」",
            "血戦「血の分水嶺」",
            "血戦「獄界視線」",
            "血戦「全霊鬼渡り」",
            "勁疾技「スリリングショット」",
            "勁疾技「ライトニングネイ」",
            "勁疾技「デンスクラウド」",
            "勁疾技「ビーストエピデミシティ」",
            "勁疾技「トライアングルチェイス」",
            "勁疾技「ブラックペガサス流星弾」",
            "勁疾技「マッスルエクスプロージョン」",
            "「フォロミーアンアフライド」",
            "「鬼形のホイポロイ」",
            "「鬼畜生の所業」",
        ),
        "th18": (
            "招符「弾幕万来」",
            "招符「弾幕万来」",
            "招符「弾幕万来」",
            "招符「弾幕万来」",
            "招符「弾災招福」",
            "招符「弾災招福」",
            "招符「弾災招福」",
            "招符「弾災招福」",
            "森符「木隠れの技術」",
            "森符「木隠れの技術」",
            "森符「極・木隠れの技術」",
            "森符「真・木隠れの技術」",
            "森符「最奥の森域」",
            "森符「最奥の森域」",
            "森符「極・最奥の森域」",
            "森符「真・最奥の森域」",
            "葉技「グリーンスパイラル」",
            "葉技「グリーンスパイラル」",
            "葉技「グリーンサイクロン」",
            "葉技「グリーントルネード」",
            "山符「動天の雲間草」",
            "山符「動天の雲間草」",
            "山怪「驚愕の雲間草」",
            "山怪「驚愕の雲間草」",
            "山符「妖光輝く薄雪草」",
            "山符「妖光輝く薄雪草」",
            "山怪「妖魔犇めく薄雪草」",
            "山怪「妖魔犇めく薄雪草」",
            "山花「殺戮の駒草」",
            "山花「殺戮の駒草」",
            "山花「殺戮の山の女王」",
            "山花「殺戮の山の女王」",
            "玉符「虹龍陰陽玉」",
            "玉符「虹龍陰陽玉」",
            "玉符「虹龍陰陽玉」",
            "玉符「陰陽神玉」",
            "玉将「クイーンオブインヤンスフィア」",
            "玉将「クイーンオブインヤンスフィア」",
            "女王珠「虹の扉の向こうに」",
            "女王珠「虹の扉の向こうに」",
            "「陰陽サフォケイション」",
            "「陰陽サフォケイション」",
            "「陰陽サフォケイション」",
            "「陰陽サフォケイション」",
            "禍星「星火燎原の舞」",
            "禍星「星火燎原の舞」",
            "禍星「星火燎原乱舞」",
            "禍星「星火燎原乱舞」",
            "星風「虹彩陸離の舞」",
            "星風「虹彩陸離の舞」",
            "星風「虹彩陸離乱舞」",
            "星風「虹彩陸離乱舞」",
            "光馬「天馬行空の舞」",
            "光馬「天馬行空の舞」",
            "光馬「天馬行空乱舞」",
            "光馬「天馬行空乱舞」",
            "虹光「光風霽月」",
            "虹光「光風霽月」",
            "虹光「光風霽月」",
            "虹光「光風霽月」",
            "「無主への供物」",
            "「無主への供物」",
            "「無主への供物」",
            "「無主への供物」",
            "「弾幕狂蒐家の妄執」",
            "「弾幕狂蒐家の妄執」",
            "「弾幕狂蒐家の妄執」",
            "「弾幕狂蒐家の妄執」",
            "「バレットマーケット」",
            "「バレットマーケット」",
            "「密度の高いバレットマーケット」",
            "「弾幕自由市場」",
            "「虹人環」",
            "「虹人環」",
            "「虹人環」",
            "「虹人環」",
            "「バレットドミニオン」",
            "「バレットドミニオン」",
            "「暴虐のバレットドミニオン」",
            "「無道のバレットドミニオン」",
            "「弾幕のアジール」",
            "「弾幕のアジール」",
            "「弾幕のアジール」",
            "「弾幕のアジール」",
            "狐符「フォックスワインダー」",
            "管狐「シリンダーフォックス」",
            "星狐「天狐龍星の舞」",
            "蠱毒「カニバリスティックインセクト」",
            "蠱毒「ケイブスウォーマー」",
            "蠱毒「スカイペンドラ」",
            "採掘「積もり続けるマインダンプ」",
            "採掘「マインブラスト」",
            "採掘「妖怪達のシールドメソッド」",
            "大蜈蚣「スネークイーター」",
            "大蜈蚣「ドラゴンイーター」",
            "「蠱毒のグルメ」",
            "「蟲姫さまの輝かしく落ち着かない毎日」",
        ),
    }
)


def _CheckDictIntegrity() -> bool:
    for i in spell_names_en:
        try:
            if len(spell_names_en[i]) != len(spell_names_jp[i]):
                return False
        except KeyError:
            return False
    return True


assert len(spell_names_en) == len(spell_names_jp)
assert _CheckDictIntegrity()


def get(game_id: str, spell_id: int):
    """
    Obtains a spell card name given a game ID and a spell ID

    Uses the language set in gettext to automatically retrieve the spell name in English or in Japanese
    """
    try:
        if get_language() == "ja":
            return spell_names_jp[game_id][spell_id]
        else:
            return spell_names_en[game_id][spell_id]
    except (IndexError, KeyError, TypeError):
        return None
