{
    "0": "Firefly Sign \"Earthly Meteor\"",
    "1": "Firefly Sign \"Earthly Comet\"",
    "2": "Lamp Sign \"Firefly Phenomenon\"",
    "3": "Lamp Sign \"Firefly Phenomenon\"",
    "4": "Lamp Sign \"Firefly Phenomenon\"",
    "5": "Lamp Sign \"Firefly Phenomenon\"",
    "6": "Wriggle Sign \"Little Bug\"",
    "7": "Wriggle Sign \"Little Bug Storm\"",
    "8": "Wriggle Sign \"Nightbug Storm\"",
    "9": "Wriggle Sign \"Nightbug Tornado\"",
    "10": "Hidden Bug \"Endless Night Seclusion\"",
    "11": "Hidden Bug \"Endless Night Seclusion\"",
    "12": "Hidden Bug \"Endless Night Seclusion\"",
    "13": "Vocal Sign \"Hooting in the Night\"",
    "14": "Vocal Sign \"Hooting in the Night\"",
    "15": "Vocal Sign \"Howl of the Horned Owl\"",
    "16": "Vocal Sign \"Howl of the Horned Owl\"",
    "17": "Moth Sign \"Hawk Moth's Insect Curse\"",
    "18": "Moth Sign \"Hawk Moth's Insect Curse\"",
    "19": "Toxin Sign \"Poisonous Moth's Scales\"",
    "20": "Deadly Toxin \"Poisonous Moth's Dance in the Dark\"",
    "21": "Hawk Sign \"Ill-Starred Dive\"",
    "22": "Hawk Sign \"Ill-Starred Dive\"",
    "23": "Hawk Sign \"Ill-Starred Dive\"",
    "24": "Hawk Sign \"Ill-Starred Dive\"",
    "25": "Night-Blindness \"Song of the Night Sparrow\"",
    "26": "Night-Blindness \"Song of the Night Sparrow\"",
    "27": "Night-Blindness \"Song of the Night Sparrow\"",
    "28": "Night-Blindness \"Song of the Night Sparrow\"",
    "29": "Night-Sparrow \"Midnight Chorus-Master\"",
    "30": "Night-Sparrow \"Midnight Chorus-Master\"",
    "31": "Night-Sparrow \"Midnight Chorus-Master\"",
    "32": "Spiritual Birth \"First Pyramid\"",
    "33": "Spiritual Birth \"First Pyramid\"",
    "34": "Spiritual Birth \"First Pyramid\"",
    "35": "Spiritual Birth \"First Pyramid\"",
    "36": "Origin Sign \"Ephemerality 137\"",
    "37": "Origin Sign \"Ephemerality 137\"",
    "38": "Origin Sign \"Ephemerality 137\"",
    "39": "Ambition Sign \"Buretsu Crisis\"",
    "40": "Ambition Sign \"Masakado Crisis\"",
    "41": "Ambition Sign \"Yoshimitsu Crisis\"",
    "42": "Ambition Sign \"General Headquarters Crisis\"",
    "43": "Land Sign \"Three Sacred Treasures - Sword\"",
    "44": "Land Sign \"Three Sacred Treasures - Orb\"",
    "45": "Land Sign \"Three Sacred Treasures - Mirror\"",
    "46": "Land Scheme \"Three Sacred Treasures - Country\"",
    "47": "Ending Sign \"Phantasmal Emperor\"",
    "48": "Ending Sign \"Phantasmal Emperor\"",
    "49": "Pseudo-History \"The Legend of Gensokyo\"",
    "50": "Pseudo-History \"The Legend of Gensokyo\"",
    "51": "Future \"Gods' Realm\"",
    "52": "Future \"Gods' Realm\"",
    "53": "Future \"Gods' Realm\"",
    "54": "Dream Sign \"Duplex Barrier\"",
    "55": "Dream Sign \"Duplex Barrier\"",
    "56": "Dream Land \"Great Duplex Barrier\"",
    "57": "Dream Land \"Great Duplex Barrier\"",
    "58": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "59": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "60": "Scattered Spirit \"Fantasy Seal -Worn-\"",
    "61": "Scattered Spirit \"Fantasy Seal -Worn-\"",
    "62": "Dream Sign \"Evil-Sealing Circle\"",
    "63": "Dream Sign \"Evil-Sealing Circle\"",
    "64": "Divine Arts \"Omnidirectional Oni-Binding Circle\"",
    "65": "Divine Arts \"Omnidirectional Dragon-Slaying Circle\"",
    "66": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "67": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "68": "Migrating Spirit \"Fantasy Seal -Marred-\"",
    "69": "Migrating Spirit \"Fantasy Seal -Marred-\"",
    "70": "Boundary \"Duplex Danmaku Barrier\"",
    "71": "Boundary \"Duplex Danmaku Barrier\"",
    "72": "Great Barrier \"Hakurei Danmaku Barrier\"",
    "73": "Great Barrier \"Hakurei Danmaku Barrier\"",
    "74": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "75": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "76": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "77": "Magic Sign \"Milky Way\"",
    "78": "Magic Sign \"Milky Way\"",
    "79": "Magic Space \"Asteroid Belt\"",
    "80": "Magic Space \"Asteroid Belt\"",
    "81": "Magic Sign \"Stardust Reverie\"",
    "82": "Magic Sign \"Stardust Reverie\"",
    "83": "Black Magic \"Event Horizon\"",
    "84": "Black Magic \"Event Horizon\"",
    "85": "Love Sign \"Non-Directional Laser\"",
    "86": "Love Sign \"Non-Directional Laser\"",
    "87": "Love Storm \"Starlight Typhoon\"",
    "88": "Love Storm \"Starlight Typhoon\"",
    "89": "Love Sign \"Master Spark\"",
    "90": "Love Sign \"Master Spark\"",
    "91": "Loving Heart \"Double Spark\"",
    "92": "Loving Heart \"Double Spark\"",
    "93": "Light Sign \"Earthlight Ray\"",
    "94": "Light Sign \"Earthlight Ray\"",
    "95": "Light Blast \"Shoot the Moon\"",
    "96": "Light Blast \"Shoot the Moon\"",
    "97": "Magicannon \"Final Spark\"",
    "98": "Magicannon \"Final Spark\"",
    "99": "Magicannon \"Final Master Spark\"",
    "100": "Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"",
    "101": "Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"",
    "102": "Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"",
    "103": "Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"",
    "104": "Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\"",
    "105": "Lunatic Sign \"Hallucinogenic Tuning (Visionary Tuning)\"",
    "106": "Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"",
    "107": "Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"",
    "108": "Loafing Sign \"Life & Spirit Stopping (Idling Wave)\"",
    "109": "Loafing Sign \"Life & Spirit Stopping (Idling Wave)\"",
    "110": "Indolence \"Life & Spirit Stopping (Mind Stopper)\"",
    "111": "Indolence \"Life & Spirit Stopping (Mind Stopper)\"",
    "112": "Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
    "113": "Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
    "114": "Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
    "115": "Spread Sign \"Moon of Truth (Invisible Full Moon)\"",
    "116": "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
    "117": "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
    "118": "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
    "119": "Spacesphere \"Earth in a Pot\"",
    "120": "Spacesphere \"Earth in a Pot\"",
    "121": "Spacesphere \"Earth in a Pot\"",
    "122": "Spacesphere \"Earth in a Pot\"",
    "123": "Awakened God \"Memories of the Age of the Gods\"",
    "124": "Awakened God \"Memories of the Age of the Gods\"",
    "125": "God Sign \"Genealogy of the Celestials\"",
    "126": "God Sign \"Genealogy of the Celestials\"",
    "127": "Revival \"Seimei Yūgi -Life Game-\"",
    "128": "Revival \"Seimei Yūgi -Life Game-\"",
    "129": "Resurrection \"Rising Game\"",
    "130": "Resurrection \"Rising Game\"",
    "131": "Leading God \"Omoikane's Device\"",
    "132": "Leading God \"Omoikane's Device\"",
    "133": "Mind of God \"Omoikane's Brain\"",
    "134": "Mind of God \"Omoikane's Brain\"",
    "135": "Curse of the Heavens \"Apollo 13\"",
    "136": "Curse of the Heavens \"Apollo 13\"",
    "137": "Curse of the Heavens \"Apollo 13\"",
    "138": "Curse of the Heavens \"Apollo 13\"",
    "139": "Esoterica \"Astronomical Entombing\"",
    "140": "Esoterica \"Astronomical Entombing\"",
    "141": "Esoterica \"Astronomical Entombing\"",
    "142": "Esoterica \"Astronomical Entombing\"",
    "143": "Forbidden Elixir \"Hourai Elixir\"",
    "144": "Forbidden Elixir \"Hourai Elixir\"",
    "145": "Forbidden Elixir \"Hourai Elixir\"",
    "146": "Forbidden Elixir \"Hourai Elixir\"",
    "147": "Medicine Sign \"Galaxy in a Pot\"",
    "148": "Medicine Sign \"Galaxy in a Pot\"",
    "149": "Medicine Sign \"Galaxy in a Pot\"",
    "150": "Medicine Sign \"Galaxy in a Pot\"",
    "151": "Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\"",
    "152": "Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\"",
    "153": "Divine Treasure \"Brilliant Dragon Bullet\"",
    "154": "Divine Treasure \"Brilliant Dragon Bullet\"",
    "155": "Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"",
    "156": "Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"",
    "157": "Divine Treasure \"Buddhist Diamond\"",
    "158": "Divine Treasure \"Buddhist Diamond\"",
    "159": "Impossible Request \"Robe of Fire Rat -Patient Mind-\"",
    "160": "Impossible Request \"Robe of Fire Rat -Patient Mind-\"",
    "161": "Divine Treasure \"Salamander Shield\"",
    "162": "Divine Treasure \"Salamander Shield\"",
    "163": "Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"",
    "164": "Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"",
    "165": "Divine Treasure \"Life Spring Infinity\"",
    "166": "Divine Treasure \"Life Spring Infinity\"",
    "167": "Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku-\"",
    "168": "Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku-\"",
    "169": "Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"",
    "170": "Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"",
    "171": "\"End of Imperishable Night -New Moon-\"",
    "172": "\"End of Imperishable Night -Crescent Moon-\"",
    "173": "\"End of Imperishable Night -1st Quarter's Moon-\"",
    "174": "\"End of Imperishable Night -Matsuyoi-\"",
    "175": "\"End of Imperishable Night -11 o'Clock-\"",
    "176": "\"End of Imperishable Night -Half to Midnight-\"",
    "177": "\"End of Imperishable Night -Midnight-\"",
    "178": "\"End of Imperishable Night -Half Past Midnight-\"",
    "179": "\"End of Imperishable Night -1 o'Clock-\"",
    "180": "\"End of Imperishable Night -Half Past 1-\"",
    "181": "\"End of Imperishable Night -Dead of Night-\"",
    "182": "\"End of Imperishable Night -Half Past 2-\"",
    "183": "\"End of Imperishable Night -3 o'Clock-\"",
    "184": "\"End of Imperishable Night -Half Past 3-\"",
    "185": "\"End of Imperishable Night -4 o'Clock-\"",
    "186": "\"End of Imperishable Night -Half Past 4-\"",
    "187": "\"End of Imperishable Night -Morning Mist-\"",
    "188": "\"End of Imperishable Night -Dawn-\"",
    "189": "\"End of Imperishable Night -Morning Star-\"",
    "190": "\"End of Imperishable Night -Rising World-\"",
    "191": "Past \"Old History of an Untrodden Land -Old History-\"",
    "192": "Reincarnation \"Ichijou Returning Bridge\"",
    "193": "Future \"New History of Fantasy -Next History-\"",
    "194": "Limiting Edict \"Curse of Tsuki-no-Iwakasa\"",
    "195": "Undying \"Fire Bird -Feng Wing Ascension-\"",
    "196": "Fujiwara \"Wounds of Metsuzai Temple\"",
    "197": "Undying \"Xu Fu's Dimension\"",
    "198": "Expiation \"Honest Man's Death\"",
    "199": "Hollow Being \"Wu\"",
    "200": "Inextinguishable \"Phoenix's Tail\"",
    "201": "Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\"",
    "202": "\"Possessed by Phoenix\"",
    "203": "\"Hourai Doll\"",
    "204": "\"Imperishable Shooting\"",
    "205": "\"Unseasonal Butterfly Storm\"",
    "206": "\"Blind Nightbird\"",
    "207": "\"Emperor of the Land of the Rising Sun\"",
    "208": "\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
    "209": "\"Heaven Spider's Butterfly-Capturing Web\"",
    "210": "\"Tree-Ocean of Hourai\"",
    "211": "\"Phoenix Rebirth\"",
    "212": "\"Ancient Duper\"",
    "213": "\"Total Purification\"",
    "214": "\"Fantasy Nature\"",
    "215": "\"Blazing Star\"",
    "216": "\"Deflation World\"",
    "217": "\"Matsuyoi-Reflecting Satellite Slash\"",
    "218": "\"The Phantom of the Grand Guignol\"",
    "219": "\"Scarlet Destiny\"",
    "220": "\"Saigyouji Parinirvana\"",
    "221": "\"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-\""
}