# Generated by Django 4.1 on 2022-08-18 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.TextField(primary_key=True, serialize=False)),
                ('has_replays', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('replay', models.BinaryField(max_length=1000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.game')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField()),
                ('video_url', models.TextField(max_length=1000)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.shot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good', models.BooleanField()),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scores.score')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(models.F('shot_id'), models.F('game'), name='unique_shot_per_game'),
        ),
    ]
