# Generated by Django 4.1 on 2022-08-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.TextField(primary_key=True, serialize=False)),
                ('has_replays', models.BooleanField()),
                ('num_difficulties', models.IntegerField()),
            ],
            options={
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='ReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.BinaryField(max_length=1000000)),
                ('is_good', models.BooleanField()),
                ('points', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Regular'), (2, 'Tas'), (3, 'Unlisted'), (4, 'Private')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.IntegerField()),
                ('points', models.BigIntegerField()),
                ('video_url', models.TextField(max_length=1000)),
                ('comment', models.TextField(max_length=50000)),
            ],
            options={
                'ordering': ['shot', 'difficulty', '-points'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('replay', models.BinaryField(max_length=1000000)),
            ],
        ),
    ]
