# Generated by Django 4.1 on 2022-08-18 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial_yay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='points',
        ),
        migrations.AddField(
            model_name='game',
            name='num_difficulties',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replayfile',
            name='points',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(default='', max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='difficulty',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
