# Generated by Django 4.1 on 2022-08-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='video_url',
            new_name='video_link',
        ),
    ]
