# Generated by Django 4.1 on 2022-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_rename_score_score_points_game_num_difficulties_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(('difficulty__gte', 0)), name='difficulty_gte_0'),
        ),
    ]
