# Generated by Django 4.1 on 2022-08-29 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_rename_video_url_score_video_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['shot', 'rep_difficulty', '-points']},
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='difficulty_gte_0',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='difficulty',
            new_name='rep_difficulty',
        ),
        migrations.RemoveField(
            model_name='replayfile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='score',
            name='video_link',
        ),
        migrations.AddField(
            model_name='replayfile',
            name='video_link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rep_clear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rep_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 0, 46, 28, 722430)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='rep_name',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='rep_points',
            field=models.BigIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='rep_slowdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rep_spellpracticeid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='replayfile',
            name='replay',
            field=models.BinaryField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(('rep_difficulty__gte', 0)), name='difficulty_gte_0'),
        ),
    ]
