# Generated by Django 4.1 on 2022-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_difficulty_gte_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Tas'), (3, 'Unlisted'), (4, 'Private')], default=1),
            preserve_default=False,
        ),
    ]
