# Generated by Django 4.1 on 2022-08-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_score_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayfile',
            name='replay',
            field=models.BinaryField(default=b'', max_length=1000000),
            preserve_default=False,
        ),
    ]
