# Generated by Django 4.1.4 on 2023-02-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_might_be_banned_ban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="reason",
            field=models.TextField(blank=True, default="default"),
            preserve_default=False,
        ),
    ]
