# Generated by Django 4.1.4 on 2023-02-09 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_deleted_on_user_deleted_on_set_iff_not_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
