# Generated by Django 4.1.4 on 2023-02-10 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_visits_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="deleted_account_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="ban",
            name="deleted_account_username",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ban",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ban",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("target__isnull", True),
                        ("deleted_account_username__isnull", False),
                        ("deleted_account_email__isnull", False),
                    ),
                    models.Q(
                        ("target__isnull", False),
                        ("deleted_account_username__isnull", True),
                        ("deleted_account_email__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="target_null_iff_deleted_account_fields_are_set",
            ),
        ),
    ]
