# Generated by Django 4.1.7 on 2023-05-09 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("replays", "0034_alter_replay_category_alter_replay_replay_type"),
        ("users", "0012_ban_deleted_account_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimReplayRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_info", models.TextField()),
                ("request_status", models.IntegerField(choices=[(1, "Submitted")])),
                ("replays", models.ManyToManyField(to="replays.replay")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
