# Generated by Django 4.1.7 on 2023-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_claimreplayrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimreplayrequest",
            name="request_status",
            field=models.IntegerField(
                choices=[
                    (1, "Submitted"),
                    (2, "Approved"),
                    (3, "User Deleted"),
                    (4, "Staff Deleted"),
                ]
            ),
        ),
    ]
