# Generated by Django 4.2.4 on 2025-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_claimreplayrequest_request_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForbiddenEmailDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.TextField()),
            ],
        ),
    ]
